{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/hyperv-srv;DataWarehouse",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "mffco-srv",
            "database": "DataWarehouse"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "Invent Trance Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "InventTranceKey"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "UnitKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusKey"
          },
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CarKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodDeliverykey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliverykey"
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey"
          },
          {
            "name": "OrderDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateAlternativeKey"
          },
          {
            "name": "ProductionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductionDateAlternativeKey"
          },
          {
            "name": "ShippingDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippingDateAlternativeKey"
          },
          {
            "name": "Sales Order",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Short Date",
            "displayFolder": "Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "sourceColumn": "ProductionDate",
            "formatString": "dd-MM-yyyy",
            "displayFolder": "Date"
          },
          {
            "name": "Shipping Date",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate",
            "formatString": "Short Date",
            "displayFolder": "Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "UnitPrice",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "SalesQty",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesQty"
          },
          {
            "name": "DiscountPercent",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountPercent"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LineAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "AmountAfterTax",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountAfterTax",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Payment",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Payment",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          },
          {
            "name": "Create Date Time",
            "dataType": "dateTime",
            "sourceColumn": "CreateDateTime",
            "displayFolder": "Date"
          },
          {
            "name": "StatusOrderKey",
            "dataType": "int64",
            "sourceColumn": "StatusOrderKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(dbo_FactSales,1,17,Replacer.ReplaceValue,{\"MethodAcquisitionKey\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value\", each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Line Amount",
            "expression": "ROUND(sum(FactSales[LineAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Amount",
            "description": "Total Amount After Tax",
            "expression": "round(sum(FactSales[AmountAfterTax]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Tax Amount",
            "expression": "round(sum(FactSales[TaxAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Payment",
            "expression": "round(sum(FactSales[Payment]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of SO",
            "expression": "DISTINCTCOUNT(FactSales[Sales Order])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Other",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Unit Price",
            "expression": "ROUND(sum(FactSales[UnitPrice]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Qty",
            "expression": "sum(FactSales[SalesQty])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Other",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Percent",
            "expression": "SUM(FactSales[DiscountPercent])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "expression": "SUM(FactSales[DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Amount",
            "expression": "MAX([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Minimum of Discount Amount",
            "expression": "MIN([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Percent",
            "expression": "MAX([DiscountPercent])",
            "displayFolder": "Discount"
          },
          {
            "name": "Minimum of DiscountPercent",
            "expression": "MIN([DiscountPercent])",
            "displayFolder": "Discount"
          },
          {
            "name": "Count Of Product",
            "expression": "DISTINCTCOUNT (FactSales[ProductKey])",
            "displayFolder": "Other"
          },
          {
            "name": "Average per Day",
            "expression": " DIVIDE(sum(FactSales[AmountAfterTax]),DISTINCTCOUNT(FactSales[Order Date])) ",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Average",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Average per Order",
            "expression": " DIVIDE(sum(FactSales[AmountAfterTax]),DISTINCTCOUNT(FactSales[Sales Order])) ",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Average",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Day",
            "expression": "DISTINCTCOUNT(FactSales[Order Date])",
            "formatString": "0"
          }
        ]
      },
      {
        "name": "DimCar",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "sourceColumn": "CarKey"
          },
          {
            "name": "CarAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CarAlternativeKey"
          },
          {
            "name": "Car Number",
            "dataType": "string",
            "sourceColumn": "CarNumber"
          },
          {
            "name": "Car Name",
            "dataType": "string",
            "sourceColumn": "CarName"
          },
          {
            "name": "Car Type",
            "dataType": "int64",
            "sourceColumn": "CarType"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCar = Source{[Schema=\"dbo\",Item=\"DimCar\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimCar, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimCompany",
        "columns": [
          {
            "name": "Companykey",
            "dataType": "int64",
            "sourceColumn": "Companykey"
          },
          {
            "name": "CompanyAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CompanyAlternativeKey"
          },
          {
            "name": "CompanyName",
            "dataType": "string",
            "sourceColumn": "CompanyName"
          },
          {
            "name": "Desc",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Desc"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCompany = Source{[Schema=\"dbo\",Item=\"DimCompany\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimCompany, each ([Companykey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "Customer No.",
            "dataType": "string",
            "sourceColumn": "CustomerAlternativeKey"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Customer Group",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "CustomerType"
          },
          {
            "name": "Classification",
            "dataType": "string",
            "sourceColumn": "CustomerClassification"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday",
            "formatString": "dd-MM-yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"dd-MM-yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          },
          {
            "name": "Age",
            "dataType": "double",
            "sourceColumn": "Age",
            "formatString": "0"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimCustomer, each ([CompanyKey] = 3)),",
                "    #\"Inserted Age\" = Table.AddColumn(#\"Filtered Rows\", \"Age\", each (Date.From(DateTime.LocalNow()) - [Birthday])/365),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted Age\",{{\"Age\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",124,0,Replacer.ReplaceValue,{\"Age\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimDimension",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "DimensionAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DimensionAlternativeKey"
          },
          {
            "name": "LocationId",
            "dataType": "string",
            "sourceColumn": "InventLocationId"
          },
          {
            "name": "Warehouse",
            "dataType": "string",
            "sourceColumn": "WarehouseName"
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "SiteName"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "ColorName"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "SizeName"
          },
          {
            "name": "Configration",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ConfigrationName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDimension = Source{[Schema=\"dbo\",Item=\"DimDimension\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimDimension, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "EmployeeID",
            "dataType": "string",
            "sourceColumn": "EmployeeAlternativeKey"
          },
          {
            "name": "Employee",
            "dataType": "string",
            "sourceColumn": "EmployeeName"
          },
          {
            "name": "Job",
            "dataType": "string",
            "sourceColumn": "Job"
          },
          {
            "name": "Departmen",
            "dataType": "string",
            "sourceColumn": "DepartmenName"
          },
          {
            "name": "Division",
            "dataType": "string",
            "sourceColumn": "DivisionName"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "Contract Type",
            "dataType": "string",
            "sourceColumn": "ContractType"
          },
          {
            "name": "ContractDate",
            "dataType": "dateTime",
            "sourceColumn": "ContractDate"
          },
          {
            "name": "Contract End Date",
            "dataType": "dateTime",
            "sourceColumn": "ContractEndDate"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "Hire Date",
            "dataType": "dateTime",
            "sourceColumn": "HireDate"
          },
          {
            "name": "InsuranceDate",
            "dataType": "dateTime",
            "sourceColumn": "InsuranceDate"
          },
          {
            "name": "Worke Status",
            "dataType": "string",
            "sourceColumn": "WorkeStatus"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          },
          {
            "name": "EmployeeNameFull",
            "dataType": "string",
            "sourceColumn": "EmployeeNameFull"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimEmployee, each ([CompanyKey] = 3)),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Filtered Rows\",{{\"EmployeeName\", Text.Clean, type text}}),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Cleaned Text\", \"Text Before Delimiter\", each Text.BeforeDelimiter([EmployeeName], \" \", 1), type text),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Text Before Delimiter\",{{\"EmployeeName\", \"EmployeeNameFull\"}, {\"Text Before Delimiter\", \"EmployeeName\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"CompanyKey\", \"EmployeeKey\", \"EmployeeAlternativeKey\", \"EmployeeNameFull\", \"EmployeeName\", \"Job\", \"DepartmenName\", \"DivisionName\", \"Gender\", \"ContractType\", \"ContractDate\", \"ContractEndDate\", \"BirthDate\", \"HireDate\", \"InsuranceDate\", \"WorkeStatus\", \"UpdatLasteTime\"})",
                "in",
                "    #\"Reordered Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimOrderStatus",
        "columns": [
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusKey"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "StatusName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixOrderStatus = Source{[Schema=\"dbo\",Item=\"DimFixOrderStatus\"]}[Data]",
                "in",
                "    dbo_DimFixOrderStatus"
              ]
            }
          }
        ]
      },
      {
        "name": "DimSalesType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "Type Name",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixSalesType = Source{[Schema=\"dbo\",Item=\"DimFixSalesType\"]}[Data]",
                "in",
                "    dbo_DimFixSalesType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "GeographyAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyAlternativeKey"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "RegionName"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "StateName"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "CityName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimGeography, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyGeography",
            "levels": [
              {
                "name": "Region",
                "ordinal": 0,
                "column": "Region"
              },
              {
                "name": "State",
                "ordinal": 1,
                "column": "State"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City"
              }
            ]
          }
        ]
      },
      {
        "name": "DimMethodAcquisition",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodAcquisitionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionAlternativeKey"
          },
          {
            "name": "Acquisition",
            "dataType": "string",
            "sourceColumn": "NameMethodAcquisition"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodAcquisition = Source{[Schema=\"dbo\",Item=\"DimMethodAcquisition\"]}[Data]",
                "in",
                "    dbo_DimMethodAcquisition"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodDelivery",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodDeliveryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliveryKey"
          },
          {
            "name": "MethodDeliveryAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliveryAlternativeKey"
          },
          {
            "name": "Delivery",
            "dataType": "string",
            "sourceColumn": "NameMethodDelivery"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodDelivery = Source{[Schema=\"dbo\",Item=\"DimMethodDelivery\"]}[Data]",
                "in",
                "    dbo_DimMethodDelivery"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodPayment",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodPaymentKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodPaymentKey"
          },
          {
            "name": "MethodPaymentAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodPaymentAlternativeKey"
          },
          {
            "name": "Payment",
            "dataType": "string",
            "sourceColumn": "NameMethodsPayment"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodPayment = Source{[Schema=\"dbo\",Item=\"DimMethodPayment\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(dbo_DimMethodPayment,\"UnKown\",\"نقدي\",Replacer.ReplaceText,{\"NameMethodsPayment\"})",
                "in",
                "    #\"Replaced Value\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimPromotion",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "PromotionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionAlternativeKey"
          },
          {
            "name": "STATUS",
            "dataType": "int64",
            "sourceColumn": "STATUS"
          },
          {
            "name": "FROMDATE",
            "dataType": "dateTime",
            "sourceColumn": "FROMDATE"
          },
          {
            "name": "TODATE",
            "dataType": "dateTime",
            "sourceColumn": "TODATE"
          },
          {
            "name": "DELIVERYDATE",
            "dataType": "dateTime",
            "sourceColumn": "DELIVERYDATE"
          },
          {
            "name": "DESCRIPTION",
            "dataType": "string",
            "sourceColumn": "DESCRIPTION"
          },
          {
            "name": "ITEMGROUP",
            "dataType": "string",
            "sourceColumn": "ITEMGROUP"
          },
          {
            "name": "DESCACTIVE",
            "dataType": "int64",
            "sourceColumn": "DESCACTIVE"
          },
          {
            "name": "SORTDISC",
            "dataType": "int64",
            "sourceColumn": "SORTDISC"
          },
          {
            "name": "PRICEDISCOUNT",
            "dataType": "decimal",
            "sourceColumn": "PRICEDISCOUNT"
          },
          {
            "name": "DISCOUNT",
            "dataType": "double",
            "sourceColumn": "DISCOUNT"
          },
          {
            "name": "QUANTITY",
            "dataType": "int64",
            "sourceColumn": "QUANTITY"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimPromotion = Source{[Schema=\"dbo\",Item=\"DimPromotion\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimPromotion, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimUnit",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "sourceColumn": "UnitKey"
          },
          {
            "name": "UnitAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "UnitAlternativeKey"
          },
          {
            "name": "UnitName",
            "dataType": "string",
            "sourceColumn": "UnitName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimUnit = Source{[Schema=\"dbo\",Item=\"DimUnit\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimUnit, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimBranche",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "Branche Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey",
            "formatString": "0",
            "sortByColumn": "Branche Sort"
          },
          {
            "name": "BrancheAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BrancheAlternativeKey"
          },
          {
            "name": "BrancheName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BrancheName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime",
            "formatString": "General Date"
          },
          {
            "name": "Branche Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheSort",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Branche",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " if([CompanyKey]==3,[BrancheName],[BrancheName] & \" \" & [CompanyKey])",
            "sortByColumn": "Branche Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimBranche = Source{[Schema=\"dbo\",Item=\"DimBranche\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(dbo_DimBranche, \"BrancheSort\", each if [BrancheAlternativeKey] = \"02\" then 1 else if [BrancheAlternativeKey] = \"06\" then 2 else if [BrancheAlternativeKey] = \"01\" then 3 else if [BrancheAlternativeKey] = \"05\" then 4 else if [BrancheAlternativeKey] = \"04\" then 5 else if [BrancheAlternativeKey] = \"03\" then 6 else if [BrancheAlternativeKey] = \"07\" then 7 else if [BrancheAlternativeKey] = \"08\" then 8 else if [BrancheAlternativeKey] = \"12\" then 9 else if [BrancheAlternativeKey] = \"13\" then 10 else 0),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Conditional Column\", each ([CompanyKey] = 3) and ([BrancheName] <> \"None\" and [BrancheName] <> \"الدور الخامس\" and [BrancheName] <> \"مخزن نصف جاهز\" and [BrancheName] <> \"نشارة\"))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "dd-MM-yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"dd-MM-yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "FullDate",
            "dataType": "string",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "int64",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "int64",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "int64",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "Season",
            "dataType": "string",
            "sourceColumn": "Season"
          },
          {
            "name": "Semester",
            "dataType": "string",
            "sourceColumn": "Semester"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          },
          {
            "name": "MM-YYYY",
            "dataType": "dateTime",
            "sourceColumn": "MM-YYYY",
            "formatString": "MM-yyyy"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimDate, each Date.IsInPreviousNYears([Date], 11) or Date.IsInCurrentYear([Date])),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Filtered Rows\", \"MM-YYYY\", each Text.Combine({DateTime.ToText([Date], \"MM\"), \"-\", DateTime.ToText([Date], \"yyyy\")}), type text),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom Column\",{{\"MM-YYYY\", type date}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyDate",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "DayOfMonth"
              }
            ]
          }
        ]
      },
      {
        "name": "FactSalesCommission",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "SalesCommissionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionKey"
          },
          {
            "name": "SalesCommissionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionAlternativeKey"
          },
          {
            "name": "TargetLevelkey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TargetLevelkey"
          },
          {
            "name": "EmpTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmpTypeKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "SalesCommissionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionDateAlternativeKey"
          },
          {
            "name": "SalesCommissionDateKey",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "SalesCommissionDateKey"
          },
          {
            "name": "Precent",
            "dataType": "double",
            "sourceColumn": "Precent"
          },
          {
            "name": "AmountFrom",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountFrom"
          },
          {
            "name": "AmountTo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountTo"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Amount"
          },
          {
            "name": "TotalSales",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TotalSales"
          },
          {
            "name": "CountSo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CountSo"
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          },
          {
            "name": "DgreeName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DimTargetLevel.DgreeName"
          },
          {
            "name": "WorkeStatus",
            "dataType": "string",
            "sourceColumn": "WorkeStatus"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSalesCommission = Source{[Schema=\"dbo\",Item=\"FactSalesCommission\"]}[Data],",
                "    #\"Expanded DimTargetLevel\" = Table.ExpandRecordColumn(dbo_FactSalesCommission, \"DimTargetLevel\", {\"DgreeName\"}, {\"DimTargetLevel.DgreeName\"}),",
                "    #\"Expanded DimEmployee\" = Table.ExpandRecordColumn(#\"Expanded DimTargetLevel\", \"DimEmployee\", {\"WorkeStatus\"}, {\"WorkeStatus\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Expanded DimEmployee\", each ([WorkeStatus] <> \"leave\"))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Commission Amount",
            "expression": "sum(FactSalesCommission[Amount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Sales",
            "expression": "sum(FactSalesCommission[TotalSales])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of SO Commission",
            "expression": "SUM(FactSalesCommission[CountSo])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Employee",
            "expression": "DISTINCTCOUNT(FactSalesCommission[EmployeeKey])"
          },
          {
            "name": "Average per Employee",
            "expression": "DIVIDE(FactSalesCommission[Commission Amount],FactSalesCommission[Count Of Employee])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Average per Month",
            "expression": "DIVIDE(FactSalesCommission[Commission Amount],FactSalesCommission[Count Of Month])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Month",
            "expression": "DISTINCTCOUNT(FactSalesCommission[SalesCommissionDateAlternativeKey])"
          },
          {
            "name": "Maximum of DgreeName",
            "expression": "MAX([DgreeName])"
          },
          {
            "name": "Maximum of TargetLevelkey",
            "expression": "sum([TargetLevelkey])"
          },
          {
            "name": "Average",
            "expression": "AVERAGE(FactSalesCommission[Amount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "DimEmpType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "TypeName",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmpType = Source{[Schema=\"dbo\",Item=\"DimEmpType\"]}[Data]",
                "in",
                "    dbo_DimEmpType"
              ]
            }
          }
        ]
      },
      {
        "name": "DateTime",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date]",
            "formatString": "dd-MM-yyyy h:mm:ss AM/PM",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"dd-MM-yyyy h:mm:ss tt\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Time",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "Now()",
            "formatString": "dd-MM-yyyy h:mm:ss AM/PM",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"dd-MM-yyyy h:mm:ss tt\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALENDAR(UTCNOW(),UTCNOW())"
            }
          }
        ]
      },
      {
        "name": "DimFixFinOffsetAccountType",
        "columns": [
          {
            "name": "OffsetAccountTypeKey",
            "dataType": "int64",
            "sourceColumn": "OffsetAccountTypeKey"
          },
          {
            "name": "OffsetAccountTypeName",
            "dataType": "string",
            "sourceColumn": "OffsetAccountTypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixFinOffsetAccountType = Source{[Schema=\"dbo\",Item=\"DimFixFinOffsetAccountType\"]}[Data]",
                "in",
                "    dbo_DimFixFinOffsetAccountType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimBank",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "BankKey",
            "dataType": "int64",
            "sourceColumn": "BankKey"
          },
          {
            "name": "BankAlternativeKey",
            "dataType": "string",
            "sourceColumn": "BankAlternativeKey"
          },
          {
            "name": "BnakName",
            "dataType": "string",
            "sourceColumn": "BnakName"
          },
          {
            "name": "BankGroupName",
            "dataType": "string",
            "sourceColumn": "BankGroupName"
          },
          {
            "name": "AccountKey",
            "dataType": "int64",
            "sourceColumn": "AccountKey"
          },
          {
            "name": "CurrencyCode",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "sourceColumn": "BrancheKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimBank = Source{[Schema=\"dbo\",Item=\"DimBank\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimBank, each ([CompanyKey] = 3) )",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimTargetLevel",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "TargetLevelKey",
            "dataType": "int64",
            "sourceColumn": "TargetLevelKey"
          },
          {
            "name": "DgreeName",
            "dataType": "string",
            "sourceColumn": "DgreeName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimTargetLevel = Source{[Schema=\"dbo\",Item=\"DimTargetLevel\"]}[Data]",
                "in",
                "    dbo_DimTargetLevel"
              ]
            }
          }
        ]
      },
      {
        "name": "FactBank",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "AccountKey",
            "dataType": "int64",
            "sourceColumn": "AccountKey"
          },
          {
            "name": "OffsetAccountKey",
            "dataType": "int64",
            "sourceColumn": "OffsetAccountKey"
          },
          {
            "name": "PaymentDateAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "PaymentDateAlternativeKey"
          },
          {
            "name": "AccountType",
            "dataType": "int64",
            "sourceColumn": "AccountType"
          },
          {
            "name": "OffsetAccountType",
            "dataType": "int64",
            "sourceColumn": "OffsetAccountType"
          },
          {
            "name": "PaymentDate",
            "dataType": "dateTime",
            "sourceColumn": "PaymentDate"
          },
          {
            "name": "JournalNum",
            "dataType": "string",
            "sourceColumn": "JournalNum"
          },
          {
            "name": "AmountDebit",
            "dataType": "double",
            "sourceColumn": "AmountDebit"
          },
          {
            "name": "AmountCredit",
            "dataType": "double",
            "sourceColumn": "AmountCredit"
          },
          {
            "name": "SalesId",
            "dataType": "string",
            "sourceColumn": "SalesId"
          },
          {
            "name": "Voucher",
            "dataType": "string",
            "sourceColumn": "Voucher"
          },
          {
            "name": "txt",
            "dataType": "string",
            "sourceColumn": "txt"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "sourceColumn": "LastupdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactBank = Source{[Schema=\"dbo\",Item=\"FactBank\"]}[Data]",
                "in",
                "    dbo_FactBank"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Amount Credit",
            "expression": "sum(FactBank[AmountCredit])"
          }
        ]
      },
      {
        "name": "FactBankCustomerPayment",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "AccountKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountKey"
          },
          {
            "name": "OffsetAccountKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OffsetAccountKey"
          },
          {
            "name": "PaymentDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentDateAlternativeKey"
          },
          {
            "name": "AccountType",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountType"
          },
          {
            "name": "OffsetAccountType",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OffsetAccountType"
          },
          {
            "name": "PaymentDate",
            "dataType": "dateTime",
            "sourceColumn": "PaymentDate"
          },
          {
            "name": "JournalNum",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "JournalNum"
          },
          {
            "name": "AmountDebit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountDebit"
          },
          {
            "name": "AmountCredit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountCredit"
          },
          {
            "name": "SalesId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesId"
          },
          {
            "name": "Voucher",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Voucher"
          },
          {
            "name": "txt",
            "dataType": "string",
            "sourceColumn": "txt"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "sourceColumn": "BrancheKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactBank = Source{[Schema=\"dbo\",Item=\"FactBank\"]}[Data],",
                "    #\"Expanded DimBank\" = Table.ExpandRecordColumn(dbo_FactBank, \"DimBank\", {\"BrancheKey\"}, {\"BrancheKey\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Expanded DimBank\", each ([BrancheKey] <> 1)),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered Rows\", each [AmountCredit] > 0),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows2\", each ([OffsetAccountType] = 6) and ([AccountType] = 1))",
                "in",
                "    #\"Filtered Rows1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Count Of  Payment",
            "expression": "COUNT(FactBankCustomerPayment[AccountKey])"
          },
          {
            "name": "Payment Customer",
            "expression": "sum(FactBankCustomerPayment[AmountCredit])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "FactSalesOrder",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "TypeKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "DiscountPercent",
            "dataType": "double",
            "sourceColumn": "DiscountPercent",
            "formatString": "#,0"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "Payment",
            "dataType": "int64",
            "sourceColumn": "Payment",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Amount",
            "dataType": "int64",
            "sourceColumn": "Amount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "AmountTax",
            "dataType": "int64",
            "sourceColumn": "AmountTax",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "StatuseOrderKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StatuseOrderKey"
          },
          {
            "name": "MethodAcquisition",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MethodAcquisition"
          },
          {
            "name": "MethodDelivery",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MethodDelivery"
          },
          {
            "name": "MethodPayment",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MethodPayment"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "ShippingDate",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate",
            "formatString": "dd-MM-yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"dd-MM-yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "OrderDateKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "OrderDateKey"
          },
          {
            "name": "ShippingDateKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ShippingDateKey"
          },
          {
            "type": "calculated",
            "name": "Payment%",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "ROUND( DIVIDE(FactSalesOrder[Payment],FactSalesOrder[Amount]),2)",
            "formatString": "0%;-0%;0%"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_FactSales,{\"ProductKey\", \"PromotionKey\", \"UnitKey\", \"UnitPrice\", \"SalesQty\", \"ProductionDate\", \"InventTranceKey\", \"DimPromotion\", \"DimUnit\", \"FactSalesTrade\", \"DimProduct\", \"DimCar\"}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Removed Columns\", {\"SalesOrderNumber\"}, {{\"Amount\", each List.Sum([AmountAfterTax]), type number}, {\"AmountTax\", each List.Sum([TaxAmount]), type number}, {\"DiscountPercent\", each List.Average([DiscountPercent]), type number}, {\"DiscountAmount\", each List.Sum([DiscountAmount]), type nullable number}, {\"Payment\", each List.Sum([Payment]), type nullable number}, {\"CompanyKey\", each List.Max([CompanyKey]), type number}, {\"BrancheKey\", each List.Max([BrancheKey]), type number}, {\"GeographyKey\", each List.Max([GeographyKey]), type nullable number}, {\"CustomerKey\", each List.Max([CustomerKey]), type number}, {\"DimensionKey\", each List.Max([DimensionKey]), type number}, {\"EmployeeKey\", each List.Max([EmployeeKey]), type number}, {\"StatuseOrderKey\", each List.Max([StatusOrderKey]), type number}, {\"TypeKey\", each List.Max([TypeKey]), type number}, {\"MethodAcquisition\", each List.Max([MethodAcquisitionKey]), type number}, {\"MethodDelivery\", each List.Max([MethodDeliverykey]), type number}, {\"MethodPayment\", each List.Max([PaymentMethodKey]), type number}, {\"OrderDate\", each List.Max([OrderDate]), type nullable date}, {\"ShippingDate\", each List.Max([ShippingDate]), type nullable date}, {\"OrderDateKey\", each List.Max([OrderDateAlternativeKey]), type number}, {\"ShippingDateKey\", each List.Max([ShippingDateAlternativeKey]), type number}})",
                "in",
                "    #\"Grouped Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales Total",
            "expression": "SUM(FactSalesOrder[Amount])"
          },
          {
            "name": "Payment Total",
            "expression": "sum(FactSalesOrder[Amount])"
          },
          {
            "name": "Payment Amount",
            "expression": "SUM(FactSalesOrder[Payment])",
            "kpi": {
              "targetExpression": "'FactSalesOrder'[Sales Total]",
              "statusGraphic": "Road Signs",
              "statusExpression": [
                "var x='FactSalesOrder'[Payment Amount]/'FactSalesOrder'[_Payment Amount Goal] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.496,-1,",
                "\t                If(x<0.99,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "49.6"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "99"
                }
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ID",
            "dataType": "int64",
            "sourceColumn": "ID"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "GROUPTYPE",
            "dataType": "string",
            "sourceColumn": "GROUPTYPE",
            "displayFolder": "ProductGroup"
          },
          {
            "name": "GROUPNAME",
            "dataType": "string",
            "sourceColumn": "GROUPNAME",
            "displayFolder": "ProductGroup"
          },
          {
            "name": "SUBCATEGORID",
            "dataType": "int64",
            "sourceColumn": "SUBCATEGORID"
          },
          {
            "name": "SUBCATEGORNAME",
            "dataType": "string",
            "sourceColumn": "SUBCATEGORNAME",
            "displayFolder": "ProductGroup"
          },
          {
            "name": "LINEID",
            "dataType": "int64",
            "sourceColumn": "LINEID"
          },
          {
            "name": "LINENAME",
            "dataType": "string",
            "sourceColumn": "LINENAME",
            "displayFolder": "ProductGroup"
          },
          {
            "name": "ProductAlternativeKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternativeKey"
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName",
            "displayFolder": "ProductGroup"
          },
          {
            "name": "CALC",
            "dataType": "int64",
            "sourceColumn": "CALC"
          },
          {
            "name": "PRICE",
            "dataType": "double",
            "sourceColumn": "PRICE"
          },
          {
            "name": "PRICEQTY",
            "dataType": "double",
            "sourceColumn": "PRICEQTY"
          },
          {
            "name": "QTY",
            "dataType": "int64",
            "sourceColumn": "QTY"
          },
          {
            "name": "PurchasePrice",
            "dataType": "decimal",
            "sourceColumn": "PurchasePrice"
          },
          {
            "name": "TOTALPRICE",
            "dataType": "decimal",
            "sourceColumn": "TOTALPRICE"
          },
          {
            "name": "DISCPERCENT",
            "dataType": "double",
            "sourceColumn": "DISCPERCENT"
          },
          {
            "name": "DISCAMOUNT",
            "dataType": "decimal",
            "sourceColumn": "DISCAMOUNT"
          },
          {
            "name": "TOTALAFTER",
            "dataType": "decimal",
            "sourceColumn": "TOTALAFTER"
          },
          {
            "name": "ListProduct",
            "dataType": "int64",
            "sourceColumn": "ListProduct"
          },
          {
            "name": "TOPCATEGORY",
            "dataType": "string",
            "sourceColumn": "TOPCATEGORY",
            "displayFolder": "ProductGroup"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Sorted Rows\" = Table.Sort(dbo_DimProduct,{{\"CALC\", Order.Descending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "#TotalAfter",
            "expression": "sum(DimProduct[TOTALAFTER])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "#DiscountAmount",
            "expression": "sum(DimProduct[DISCAMOUNT])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "#TotalPrice",
            "expression": "sum(DimProduct[TOTALPRICE])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "#PurchasePrice",
            "expression": "sum(DimProduct[PurchasePrice])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "#TotalAfterMin",
            "expression": "MIN(DimProduct[TOTALAFTER])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "#TotalAfterMax",
            "expression": "MAX(DimProduct[TOTALAFTER])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "DimProductSales",
        "columns": [
          {
            "name": "SUBCATEGORNAME",
            "dataType": "string",
            "sourceColumn": "SUBCATEGORNAME"
          },
          {
            "name": "Total",
            "dataType": "double",
            "sourceColumn": "Total"
          },
          {
            "name": "ID",
            "dataType": "double",
            "sourceColumn": "ID"
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group"
          },
          {
            "name": "TopGroup",
            "dataType": "string",
            "sourceColumn": "TopGroup"
          },
          {
            "name": "Price",
            "dataType": "double",
            "sourceColumn": "Price"
          },
          {
            "name": "DiscPrec",
            "dataType": "double",
            "sourceColumn": "DiscPrec"
          },
          {
            "name": "DiscAmount",
            "dataType": "double",
            "sourceColumn": "DiscAmount"
          },
          {
            "name": "GroupType",
            "dataType": "string",
            "sourceColumn": "GroupType"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Sorted Rows\" = Table.Sort(dbo_DimProduct,{{\"CALC\", Order.Descending}}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Sorted Rows\", {\"SUBCATEGORNAME\"}, {{\"Total\", each List.Sum([TOTALAFTER]), type number}, {\"ID\", each List.Min([SUBCATEGORID]), type number}, {\"Group\", each List.Min([GROUPNAME]), type text}, {\"TopGroup\", each List.Min([TOPCATEGORY]), type text}, {\"Price\", each List.Sum([TOTALPRICE]), type number}, {\"DiscPrec\", each List.Min([DISCPERCENT]), type number}, {\"DiscAmount\", each List.Sum([DISCAMOUNT]), type number}, {\"GroupType\", each List.Min([GROUPTYPE]), type text}}),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Grouped Rows\",{{\"ID\", Order.Ascending}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Sorted Rows1\", each ([SUBCATEGORNAME] <> \"\")),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",\"انتريهات زان\",\"انتريهات\",Replacer.ReplaceText,{\"Group\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"انتريهات مكسي\",\"انتريهات\",Replacer.ReplaceText,{\"Group\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"انتريهات الموردين\",\"انتريهات\",Replacer.ReplaceText,{\"Group\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"صالونات الموردين\",\"صالونات\",Replacer.ReplaceText,{\"Group\"})",
                "in",
                "    #\"Replaced Value3\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "TotalSum",
            "expression": "sum(DimProductSales[Total])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "TotalAmount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "TotaMin",
            "expression": "Min(DimProductSales[Total])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "TotalAmount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "TotalMax",
            "expression": "Max(DimProductSales[Total])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "TotalAmount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "ProductCount",
            "expression": "COUNT(DimProductSales[SUBCATEGORNAME])",
            "formatString": "0",
            "displayFolder": "Count"
          },
          {
            "name": "GroupCount",
            "expression": "DISTINCTCOUNT(DimProductSales[Group])",
            "displayFolder": "Count"
          },
          {
            "name": "DiscMin",
            "expression": "Min(DimProductSales[DiscPrec])",
            "formatString": "0",
            "displayFolder": "Discount"
          },
          {
            "name": "DiscMax",
            "expression": "max(DimProductSales[DiscPrec])",
            "formatString": "0",
            "displayFolder": "Discount"
          },
          {
            "name": "DiscAvg",
            "expression": "AVERAGE(DimProductSales[DiscPrec])",
            "formatString": "0",
            "displayFolder": "Discount"
          },
          {
            "name": "TotaAvg",
            "expression": "AVERAGE(DimProductSales[Total])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "TotalAmount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PriceSum",
            "expression": "sum(DimProductSales[Price])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PriceAvg",
            "expression": "AVERAGE(DimProductSales[Price])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Price",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "efcc7883-a565-4dfd-9a51-1b3ee580e8a7",
        "fromTable": "FactSales",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "20a4f5a8-dc1b-425c-b945-32227fcfc412",
        "fromTable": "FactSales",
        "fromColumn": "StatusKey",
        "toTable": "DimOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "6f52df78-743c-42be-9b14-6b7827a890b0",
        "fromTable": "FactSales",
        "fromColumn": "TypeKey",
        "toTable": "DimSalesType",
        "toColumn": "TypeKey"
      },
      {
        "name": "a8a9a89f-90b1-4ebc-9808-8437e634cfe2",
        "fromTable": "FactSales",
        "fromColumn": "CarKey",
        "toTable": "DimCar",
        "toColumn": "CarKey"
      },
      {
        "name": "671e7041-af90-4534-9e1d-bf70eee94922",
        "fromTable": "FactSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "75b87e4a-c9f4-4381-a2a8-f1fa8687c0fe",
        "fromTable": "FactSales",
        "fromColumn": "DimensionKey",
        "toTable": "DimDimension",
        "toColumn": "DimensionKey"
      },
      {
        "name": "081c882e-a615-4c92-97e5-0d90b34e3524",
        "fromTable": "FactSales",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "7bfbef40-1be6-47d8-b553-00605b9e71fe",
        "fromTable": "FactSales",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "5abc277d-ce70-4f78-996a-190d3de74032",
        "fromTable": "FactSales",
        "fromColumn": "MethodAcquisitionKey",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "d223a52a-cb58-44b7-ae13-70135d56570b",
        "fromTable": "FactSales",
        "fromColumn": "MethodDeliverykey",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "934f097e-9a0a-4860-838e-901584f6065f",
        "fromTable": "FactSales",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "6d62c46f-4e0d-48d7-a479-b881f40f845c",
        "fromTable": "FactSales",
        "fromColumn": "PromotionKey",
        "toTable": "DimPromotion",
        "toColumn": "PromotionKey"
      },
      {
        "name": "a6c99fd9-5295-4781-9f3c-11d58f62b6cc",
        "fromTable": "FactSales",
        "fromColumn": "UnitKey",
        "toTable": "DimUnit",
        "toColumn": "UnitKey"
      },
      {
        "name": "88ffaa6a-2caf-46f6-b43e-8544725699d2",
        "fromTable": "FactSales",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "c4fd38a7-8477-4bac-8505-702a11a9ba54",
        "fromTable": "FactSales",
        "fromColumn": "ProductionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "a34a0957-168b-4eef-9dac-64692bcac096",
        "fromTable": "FactSales",
        "fromColumn": "ShippingDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "b862e642-d68d-4d26-83ad-2f444abcf77b",
        "fromTable": "FactSales",
        "fromColumn": "OrderDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "a7a51300-dc16-4fa7-96d6-ee1b8d060343",
        "fromTable": "FactSalesCommission",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "fec133e3-e7be-4e46-94b9-f992582d577d",
        "fromTable": "FactSalesCommission",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "1ee28abb-ea43-4b08-8f26-7f3def0ff1bd",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "4cdf3c14-110c-49b2-bcd0-3509dd9c937e",
        "fromTable": "FactSalesCommission",
        "fromColumn": "SalesCommissionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "72095038-4166-48fe-9088-9d9dbd41b74d",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmpTypeKey",
        "toTable": "DimEmpType",
        "toColumn": "TypeKey"
      },
      {
        "name": "31314b21-1e75-4df0-ada6-262091529533",
        "fromTable": "FactSalesCommission",
        "fromColumn": "TargetLevelkey",
        "toTable": "DimTargetLevel",
        "toColumn": "TargetLevelKey"
      },
      {
        "name": "a1a71b6b-9437-4842-b472-903eb573eed2",
        "fromTable": "FactBank",
        "fromColumn": "PaymentDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "89f41b39-a675-428a-9641-a92fb3a81cda",
        "fromTable": "FactBank",
        "fromColumn": "OffsetAccountType",
        "toTable": "DimFixFinOffsetAccountType",
        "toColumn": "OffsetAccountTypeKey"
      },
      {
        "name": "36dc909d-d016-44a6-b86a-f733b64d1aca",
        "fromTable": "FactBank",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "bd0e2612-6e37-483f-97e9-86b29a71404b",
        "fromTable": "FactBank",
        "fromColumn": "OffsetAccountKey",
        "toTable": "DimBank",
        "toColumn": "BankKey"
      },
      {
        "name": "4125f01c-a35c-4e85-a1ae-4ba15ac5c547",
        "fromTable": "FactBankCustomerPayment",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "4a232a1c-ef58-47b8-99b2-5b2e9fae2811",
        "fromTable": "FactBankCustomerPayment",
        "fromColumn": "PaymentDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "1ea4f856-b8be-41e0-aa35-71a3d04d130c",
        "fromTable": "FactBankCustomerPayment",
        "fromColumn": "OffsetAccountKey",
        "toTable": "DimBank",
        "toColumn": "BankKey"
      },
      {
        "name": "171ee69c-d33f-4f56-8a00-d9adb8a4438b",
        "fromTable": "FactBankCustomerPayment",
        "fromColumn": "OffsetAccountType",
        "toTable": "DimFixFinOffsetAccountType",
        "toColumn": "OffsetAccountTypeKey"
      },
      {
        "name": "8145862e-87cf-4506-80d8-f322ea1b9831",
        "fromTable": "FactBankCustomerPayment",
        "fromColumn": "AccountKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "018c7bb7-ebc7-45ae-88bb-467d2539ce43",
        "fromTable": "DimBank",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "6bfc5457-dc52-48f3-9969-580b60aa31a3",
        "fromTable": "FactSalesOrder",
        "fromColumn": "OrderDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "f10f38fa-286e-40de-8fcd-3d28cd726609",
        "fromTable": "FactSalesOrder",
        "fromColumn": "ShippingDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "8213f454-8571-4e2e-9c13-4b6646021f76",
        "fromTable": "FactSalesOrder",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "39fc5752-3ada-4004-b8b3-13cb5b64f11e",
        "fromTable": "FactSalesOrder",
        "fromColumn": "MethodPayment",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "547d468d-6d76-4758-ae8e-e9eaefcd5ca8",
        "fromTable": "FactSalesOrder",
        "fromColumn": "MethodDelivery",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "d75d20f3-5ec7-409e-aa31-81c4b6d471bc",
        "fromTable": "FactSalesOrder",
        "fromColumn": "MethodAcquisition",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "225caf7b-7356-43cd-a81d-122f9ec8fd8f",
        "fromTable": "FactSalesOrder",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "bd8558dd-180f-4eb5-8545-f43b97ec5d06",
        "fromTable": "FactSalesOrder",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "b2d61798-4ccf-4a95-b89b-7a328cc35007",
        "fromTable": "FactSalesOrder",
        "fromColumn": "TypeKey",
        "toTable": "DimSalesType",
        "toColumn": "TypeKey"
      },
      {
        "name": "5b1ae2fd-d275-43db-8102-ce9b53bf89b7",
        "fromTable": "FactSalesOrder",
        "fromColumn": "StatuseOrderKey",
        "toTable": "DimOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "1be9b562-0311-4f34-84ab-269aa8b2b6eb",
        "fromTable": "FactSalesOrder",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "b45ca210-9b78-433c-85dc-a9cdc4a865c0",
        "fromTable": "FactSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      }
    ],
    "cultures": [
      {
        "name": "ar-EG"
      }
    ],
    "perspectives": [
      {
        "name": "Payment Perspective",
        "tables": [
          {
            "name": "DimBank",
            "columns": [
              {
                "name": "AccountKey"
              },
              {
                "name": "BankAlternativeKey"
              },
              {
                "name": "BankGroupName"
              },
              {
                "name": "BankKey"
              },
              {
                "name": "BnakName"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "CurrencyCode"
              },
              {
                "name": "UpdatLasteTime"
              },
              {
                "name": "BrancheKey"
              }
            ]
          },
          {
            "name": "DimCompany",
            "columns": [
              {
                "name": "CompanyAlternativeKey"
              },
              {
                "name": "Companykey"
              },
              {
                "name": "CompanyName"
              },
              {
                "name": "Desc"
              }
            ]
          },
          {
            "name": "DimCustomer",
            "columns": [
              {
                "name": "Age"
              },
              {
                "name": "Birthday"
              },
              {
                "name": "Classification"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Customer"
              },
              {
                "name": "Customer Group"
              },
              {
                "name": "Customer No."
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Type"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayName"
              },
              {
                "name": "DayOfMonth"
              },
              {
                "name": "DayOfQuarter"
              },
              {
                "name": "DayOfWeek"
              },
              {
                "name": "DayOfWeekInMonth"
              },
              {
                "name": "DayOfWeekInYear"
              },
              {
                "name": "DayOfYear"
              },
              {
                "name": "DaySuffix"
              },
              {
                "name": "FirstDayOfMonth"
              },
              {
                "name": "FirstDayOfQuarter"
              },
              {
                "name": "FirstDayOfYear"
              },
              {
                "name": "FullDate"
              },
              {
                "name": "HolidayName"
              },
              {
                "name": "IsHoliday"
              },
              {
                "name": "LastDayOfMonth"
              },
              {
                "name": "LastDayOfQuarter"
              },
              {
                "name": "LastDayOfYear"
              },
              {
                "name": "MMYYYY"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "MonthOfQuarter"
              },
              {
                "name": "MonthYear"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "QuarterName"
              },
              {
                "name": "Season"
              },
              {
                "name": "Semester"
              },
              {
                "name": "WeekOfMonth"
              },
              {
                "name": "WeekOfQuarter"
              },
              {
                "name": "WeekOfYear"
              },
              {
                "name": "Year"
              },
              {
                "name": "YearName"
              },
              {
                "name": "MM-YYYY"
              }
            ],
            "hierarchies": [
              {
                "name": "HierarchyDate"
              }
            ]
          },
          {
            "name": "DimFixFinOffsetAccountType",
            "columns": [
              {
                "name": "OffsetAccountTypeKey"
              },
              {
                "name": "OffsetAccountTypeName"
              }
            ]
          },
          {
            "name": "FactBankCustomerPayment",
            "columns": [
              {
                "name": "AccountKey"
              },
              {
                "name": "AccountType"
              },
              {
                "name": "AmountCredit"
              },
              {
                "name": "AmountDebit"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Id"
              },
              {
                "name": "JournalNum"
              },
              {
                "name": "LastupdateDate"
              },
              {
                "name": "OffsetAccountKey"
              },
              {
                "name": "OffsetAccountType"
              },
              {
                "name": "PaymentDate"
              },
              {
                "name": "PaymentDateAlternativeKey"
              },
              {
                "name": "SalesId"
              },
              {
                "name": "txt"
              },
              {
                "name": "Voucher"
              },
              {
                "name": "BrancheKey"
              }
            ],
            "measures": [
              {
                "name": "Count Of  Payment"
              },
              {
                "name": "Payment Customer"
              }
            ]
          },
          {
            "name": "DimBranche",
            "columns": [
              {
                "name": "Branche"
              },
              {
                "name": "Branche Key"
              },
              {
                "name": "Branche Sort"
              },
              {
                "name": "BrancheAlternativeKey"
              },
              {
                "name": "BrancheName"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DateTime",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Time"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Commission Perspective",
        "tables": [
          {
            "name": "DimBranche",
            "columns": [
              {
                "name": "Branche"
              },
              {
                "name": "Branche Key"
              },
              {
                "name": "Branche Sort"
              },
              {
                "name": "BrancheAlternativeKey"
              },
              {
                "name": "BrancheName"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimCompany",
            "columns": [
              {
                "name": "CompanyAlternativeKey"
              },
              {
                "name": "Companykey"
              },
              {
                "name": "CompanyName"
              },
              {
                "name": "Desc"
              }
            ]
          },
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayName"
              },
              {
                "name": "DayOfMonth"
              },
              {
                "name": "DayOfQuarter"
              },
              {
                "name": "DayOfWeek"
              },
              {
                "name": "DayOfWeekInMonth"
              },
              {
                "name": "DayOfWeekInYear"
              },
              {
                "name": "DayOfYear"
              },
              {
                "name": "DaySuffix"
              },
              {
                "name": "FirstDayOfMonth"
              },
              {
                "name": "FirstDayOfQuarter"
              },
              {
                "name": "FirstDayOfYear"
              },
              {
                "name": "FullDate"
              },
              {
                "name": "HolidayName"
              },
              {
                "name": "IsHoliday"
              },
              {
                "name": "LastDayOfMonth"
              },
              {
                "name": "LastDayOfQuarter"
              },
              {
                "name": "LastDayOfYear"
              },
              {
                "name": "MMYYYY"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "MonthOfQuarter"
              },
              {
                "name": "MonthYear"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "QuarterName"
              },
              {
                "name": "Season"
              },
              {
                "name": "Semester"
              },
              {
                "name": "WeekOfMonth"
              },
              {
                "name": "WeekOfQuarter"
              },
              {
                "name": "WeekOfYear"
              },
              {
                "name": "Year"
              },
              {
                "name": "YearName"
              },
              {
                "name": "MM-YYYY"
              }
            ],
            "hierarchies": [
              {
                "name": "HierarchyDate"
              }
            ]
          },
          {
            "name": "DimEmployee",
            "columns": [
              {
                "name": "BirthDate"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Contract End Date"
              },
              {
                "name": "Contract Type"
              },
              {
                "name": "ContractDate"
              },
              {
                "name": "Departmen"
              },
              {
                "name": "Division"
              },
              {
                "name": "Employee"
              },
              {
                "name": "EmployeeID"
              },
              {
                "name": "EmployeeKey"
              },
              {
                "name": "EmployeeNameFull"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Hire Date"
              },
              {
                "name": "InsuranceDate"
              },
              {
                "name": "Job"
              },
              {
                "name": "UpdatLasteTime"
              },
              {
                "name": "Worke Status"
              }
            ]
          },
          {
            "name": "DimEmpType",
            "columns": [
              {
                "name": "TypeKey"
              },
              {
                "name": "TypeName"
              }
            ]
          },
          {
            "name": "DimTargetLevel",
            "columns": [
              {
                "name": "CompanyKey"
              },
              {
                "name": "DgreeName"
              },
              {
                "name": "TargetLevelKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "FactSalesCommission",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "AmountFrom"
              },
              {
                "name": "AmountTo"
              },
              {
                "name": "BrancheKey"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "CountSo"
              },
              {
                "name": "DgreeName"
              },
              {
                "name": "EmployeeKey"
              },
              {
                "name": "EmpTypeKey"
              },
              {
                "name": "IsDeleted"
              },
              {
                "name": "LastupdateDate"
              },
              {
                "name": "Precent"
              },
              {
                "name": "SalesCommissionAlternativeKey"
              },
              {
                "name": "SalesCommissionDateAlternativeKey"
              },
              {
                "name": "SalesCommissionDateKey"
              },
              {
                "name": "SalesCommissionKey"
              },
              {
                "name": "TargetLevelkey"
              },
              {
                "name": "TotalSales"
              },
              {
                "name": "WorkeStatus"
              }
            ],
            "measures": [
              {
                "name": "Average"
              },
              {
                "name": "Average per Employee"
              },
              {
                "name": "Average per Month"
              },
              {
                "name": "Commission Amount"
              },
              {
                "name": "Count Of Employee"
              },
              {
                "name": "Count Of Month"
              },
              {
                "name": "Count Of SO Commission"
              },
              {
                "name": "Maximum of DgreeName"
              },
              {
                "name": "Maximum of TargetLevelkey"
              },
              {
                "name": "Total Sales"
              }
            ]
          },
          {
            "name": "DateTime",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Time"
              }
            ]
          },
          {
            "name": "DimProduct",
            "columns": [
              {
                "name": "CompanyKey"
              },
              {
                "name": "ID"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "GROUPTYPE"
              },
              {
                "name": "GROUPNAME"
              },
              {
                "name": "SUBCATEGORID"
              },
              {
                "name": "SUBCATEGORNAME"
              },
              {
                "name": "LINEID"
              },
              {
                "name": "LINENAME"
              },
              {
                "name": "ProductAlternativeKey"
              },
              {
                "name": "ProductName"
              },
              {
                "name": "CALC"
              },
              {
                "name": "PRICE"
              },
              {
                "name": "PRICEQTY"
              },
              {
                "name": "QTY"
              },
              {
                "name": "PurchasePrice"
              },
              {
                "name": "TOTALPRICE"
              },
              {
                "name": "DISCPERCENT"
              },
              {
                "name": "DISCAMOUNT"
              },
              {
                "name": "TOTALAFTER"
              },
              {
                "name": "ListProduct"
              },
              {
                "name": "TOPCATEGORY"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Perspective",
        "tables": [
          {
            "name": "DateTime",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Time"
              }
            ]
          },
          {
            "name": "DimBranche",
            "columns": [
              {
                "name": "Branche"
              },
              {
                "name": "Branche Key"
              },
              {
                "name": "Branche Sort"
              },
              {
                "name": "BrancheAlternativeKey"
              },
              {
                "name": "BrancheName"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimCustomer",
            "columns": [
              {
                "name": "Age"
              },
              {
                "name": "Birthday"
              },
              {
                "name": "Classification"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Customer"
              },
              {
                "name": "Customer Group"
              },
              {
                "name": "Customer No."
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Type"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayName"
              },
              {
                "name": "DayOfMonth"
              },
              {
                "name": "DayOfQuarter"
              },
              {
                "name": "DayOfWeek"
              },
              {
                "name": "DayOfWeekInMonth"
              },
              {
                "name": "DayOfWeekInYear"
              },
              {
                "name": "DayOfYear"
              },
              {
                "name": "DaySuffix"
              },
              {
                "name": "FirstDayOfMonth"
              },
              {
                "name": "FirstDayOfQuarter"
              },
              {
                "name": "FirstDayOfYear"
              },
              {
                "name": "FullDate"
              },
              {
                "name": "HolidayName"
              },
              {
                "name": "IsHoliday"
              },
              {
                "name": "LastDayOfMonth"
              },
              {
                "name": "LastDayOfQuarter"
              },
              {
                "name": "LastDayOfYear"
              },
              {
                "name": "MMYYYY"
              },
              {
                "name": "MM-YYYY"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "MonthOfQuarter"
              },
              {
                "name": "MonthYear"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "QuarterName"
              },
              {
                "name": "Season"
              },
              {
                "name": "Semester"
              },
              {
                "name": "WeekOfMonth"
              },
              {
                "name": "WeekOfQuarter"
              },
              {
                "name": "WeekOfYear"
              },
              {
                "name": "Year"
              },
              {
                "name": "YearName"
              }
            ],
            "hierarchies": [
              {
                "name": "HierarchyDate"
              }
            ]
          },
          {
            "name": "DimDimension",
            "columns": [
              {
                "name": "Color"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Configration"
              },
              {
                "name": "DimensionAlternativeKey"
              },
              {
                "name": "DimensionKey"
              },
              {
                "name": "LocationId"
              },
              {
                "name": "Site"
              },
              {
                "name": "Size"
              },
              {
                "name": "UpdatLasteTime"
              },
              {
                "name": "Warehouse"
              }
            ]
          },
          {
            "name": "DimEmployee",
            "columns": [
              {
                "name": "BirthDate"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Contract End Date"
              },
              {
                "name": "Contract Type"
              },
              {
                "name": "ContractDate"
              },
              {
                "name": "Departmen"
              },
              {
                "name": "Division"
              },
              {
                "name": "Employee"
              },
              {
                "name": "EmployeeID"
              },
              {
                "name": "EmployeeKey"
              },
              {
                "name": "EmployeeNameFull"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Hire Date"
              },
              {
                "name": "InsuranceDate"
              },
              {
                "name": "Job"
              },
              {
                "name": "UpdatLasteTime"
              },
              {
                "name": "Worke Status"
              }
            ]
          },
          {
            "name": "DimGeography",
            "columns": [
              {
                "name": "City"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "GeographyAlternativeKey"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "Region"
              },
              {
                "name": "State"
              },
              {
                "name": "UpdatLasteTime"
              }
            ],
            "hierarchies": [
              {
                "name": "HierarchyGeography"
              }
            ]
          },
          {
            "name": "DimMethodAcquisition",
            "columns": [
              {
                "name": "Acquisition"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "MethodAcquisitionAlternativeKey"
              },
              {
                "name": "MethodAcquisitionKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimMethodDelivery",
            "columns": [
              {
                "name": "CompanyKey"
              },
              {
                "name": "Delivery"
              },
              {
                "name": "MethodDeliveryAlternativeKey"
              },
              {
                "name": "MethodDeliveryKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimMethodPayment",
            "columns": [
              {
                "name": "CompanyKey"
              },
              {
                "name": "MethodPaymentAlternativeKey"
              },
              {
                "name": "MethodPaymentKey"
              },
              {
                "name": "Payment"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimOrderStatus",
            "columns": [
              {
                "name": "Status"
              },
              {
                "name": "StatusKey"
              }
            ]
          },
          {
            "name": "DimPromotion",
            "columns": [
              {
                "name": "CompanyKey"
              },
              {
                "name": "DELIVERYDATE"
              },
              {
                "name": "DESCACTIVE"
              },
              {
                "name": "DESCRIPTION"
              },
              {
                "name": "DISCOUNT"
              },
              {
                "name": "FROMDATE"
              },
              {
                "name": "ITEMGROUP"
              },
              {
                "name": "Location"
              },
              {
                "name": "PRICEDISCOUNT"
              },
              {
                "name": "PromotionAlternativeKey"
              },
              {
                "name": "PromotionKey"
              },
              {
                "name": "QUANTITY"
              },
              {
                "name": "SORTDISC"
              },
              {
                "name": "STATUS"
              },
              {
                "name": "TODATE"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimSalesType",
            "columns": [
              {
                "name": "Type Name"
              },
              {
                "name": "TypeKey"
              }
            ]
          },
          {
            "name": "FactSales",
            "columns": [
              {
                "name": "AmountAfterTax"
              },
              {
                "name": "BrancheKey"
              },
              {
                "name": "CarKey"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Create Date Time"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "DimensionKey"
              },
              {
                "name": "DiscountAmount"
              },
              {
                "name": "DiscountPercent"
              },
              {
                "name": "EmployeeKey"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "Invent Trance Key"
              },
              {
                "name": "IsDeleted"
              },
              {
                "name": "LastupdateDate"
              },
              {
                "name": "LineAmount"
              },
              {
                "name": "MethodAcquisitionKey"
              },
              {
                "name": "MethodDeliverykey"
              },
              {
                "name": "Order Date"
              },
              {
                "name": "OrderDateAlternativeKey"
              },
              {
                "name": "Payment"
              },
              {
                "name": "PaymentMethodKey"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "ProductionDateAlternativeKey"
              },
              {
                "name": "ProductKey"
              },
              {
                "name": "PromotionKey"
              },
              {
                "name": "Sales Order"
              },
              {
                "name": "SalesOrderLineNumber"
              },
              {
                "name": "SalesQty"
              },
              {
                "name": "Shipping Date"
              },
              {
                "name": "ShippingDateAlternativeKey"
              },
              {
                "name": "StatusKey"
              },
              {
                "name": "StatusOrderKey"
              },
              {
                "name": "TaxAmount"
              },
              {
                "name": "TypeKey"
              },
              {
                "name": "UnitKey"
              },
              {
                "name": "UnitPrice"
              }
            ],
            "measures": [
              {
                "name": "Average per Day"
              },
              {
                "name": "Average per Order"
              },
              {
                "name": "Count Of Day"
              },
              {
                "name": "Count Of Product"
              },
              {
                "name": "Count Of Qty"
              },
              {
                "name": "Count Of SO"
              },
              {
                "name": "Discount Amount"
              },
              {
                "name": "Discount Percent"
              },
              {
                "name": "Line Amount"
              },
              {
                "name": "Maximum of Discount Amount"
              },
              {
                "name": "Maximum of Discount Percent"
              },
              {
                "name": "Minimum of Discount Amount"
              },
              {
                "name": "Minimum of DiscountPercent"
              },
              {
                "name": "Tax Amount"
              },
              {
                "name": "Total Amount"
              },
              {
                "name": "Total Payment"
              },
              {
                "name": "Unit Price"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Order Perspective",
        "tables": [
          {
            "name": "DateTime",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Time"
              }
            ]
          },
          {
            "name": "DimBranche",
            "columns": [
              {
                "name": "Branche"
              },
              {
                "name": "Branche Key"
              },
              {
                "name": "Branche Sort"
              },
              {
                "name": "BrancheAlternativeKey"
              },
              {
                "name": "BrancheName"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimCompany",
            "columns": [
              {
                "name": "CompanyAlternativeKey"
              },
              {
                "name": "Companykey"
              },
              {
                "name": "CompanyName"
              },
              {
                "name": "Desc"
              }
            ]
          },
          {
            "name": "DimCustomer",
            "columns": [
              {
                "name": "Age"
              },
              {
                "name": "Birthday"
              },
              {
                "name": "Classification"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Customer"
              },
              {
                "name": "Customer Group"
              },
              {
                "name": "Customer No."
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Type"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayName"
              },
              {
                "name": "DayOfMonth"
              },
              {
                "name": "DayOfQuarter"
              },
              {
                "name": "DayOfWeek"
              },
              {
                "name": "DayOfWeekInMonth"
              },
              {
                "name": "DayOfWeekInYear"
              },
              {
                "name": "DayOfYear"
              },
              {
                "name": "DaySuffix"
              },
              {
                "name": "FirstDayOfMonth"
              },
              {
                "name": "FirstDayOfQuarter"
              },
              {
                "name": "FirstDayOfYear"
              },
              {
                "name": "FullDate"
              },
              {
                "name": "HolidayName"
              },
              {
                "name": "IsHoliday"
              },
              {
                "name": "LastDayOfMonth"
              },
              {
                "name": "LastDayOfQuarter"
              },
              {
                "name": "LastDayOfYear"
              },
              {
                "name": "MMYYYY"
              },
              {
                "name": "MM-YYYY"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "MonthOfQuarter"
              },
              {
                "name": "MonthYear"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "QuarterName"
              },
              {
                "name": "Season"
              },
              {
                "name": "Semester"
              },
              {
                "name": "WeekOfMonth"
              },
              {
                "name": "WeekOfQuarter"
              },
              {
                "name": "WeekOfYear"
              },
              {
                "name": "Year"
              },
              {
                "name": "YearName"
              }
            ],
            "hierarchies": [
              {
                "name": "HierarchyDate"
              }
            ]
          },
          {
            "name": "DimEmployee",
            "columns": [
              {
                "name": "BirthDate"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "Contract End Date"
              },
              {
                "name": "Contract Type"
              },
              {
                "name": "ContractDate"
              },
              {
                "name": "Departmen"
              },
              {
                "name": "Division"
              },
              {
                "name": "Employee"
              },
              {
                "name": "EmployeeID"
              },
              {
                "name": "EmployeeKey"
              },
              {
                "name": "EmployeeNameFull"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Hire Date"
              },
              {
                "name": "InsuranceDate"
              },
              {
                "name": "Job"
              },
              {
                "name": "UpdatLasteTime"
              },
              {
                "name": "Worke Status"
              }
            ]
          },
          {
            "name": "DimGeography",
            "columns": [
              {
                "name": "City"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "GeographyAlternativeKey"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "Region"
              },
              {
                "name": "State"
              },
              {
                "name": "UpdatLasteTime"
              }
            ],
            "hierarchies": [
              {
                "name": "HierarchyGeography"
              }
            ]
          },
          {
            "name": "DimMethodAcquisition",
            "columns": [
              {
                "name": "Acquisition"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "MethodAcquisitionAlternativeKey"
              },
              {
                "name": "MethodAcquisitionKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimMethodDelivery",
            "columns": [
              {
                "name": "CompanyKey"
              },
              {
                "name": "Delivery"
              },
              {
                "name": "MethodDeliveryAlternativeKey"
              },
              {
                "name": "MethodDeliveryKey"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimMethodPayment",
            "columns": [
              {
                "name": "CompanyKey"
              },
              {
                "name": "MethodPaymentAlternativeKey"
              },
              {
                "name": "MethodPaymentKey"
              },
              {
                "name": "Payment"
              },
              {
                "name": "UpdatLasteTime"
              }
            ]
          },
          {
            "name": "DimOrderStatus",
            "columns": [
              {
                "name": "Status"
              },
              {
                "name": "StatusKey"
              }
            ]
          },
          {
            "name": "DimSalesType",
            "columns": [
              {
                "name": "Type Name"
              },
              {
                "name": "TypeKey"
              }
            ]
          },
          {
            "name": "FactSalesOrder",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "AmountTax"
              },
              {
                "name": "BrancheKey"
              },
              {
                "name": "CompanyKey"
              },
              {
                "name": "CustomerKey"
              },
              {
                "name": "DimensionKey"
              },
              {
                "name": "DiscountAmount"
              },
              {
                "name": "DiscountPercent"
              },
              {
                "name": "EmployeeKey"
              },
              {
                "name": "GeographyKey"
              },
              {
                "name": "MethodAcquisition"
              },
              {
                "name": "MethodDelivery"
              },
              {
                "name": "MethodPayment"
              },
              {
                "name": "OrderDate"
              },
              {
                "name": "OrderDateKey"
              },
              {
                "name": "Payment"
              },
              {
                "name": "SalesOrderNumber"
              },
              {
                "name": "ShippingDate"
              },
              {
                "name": "ShippingDateKey"
              },
              {
                "name": "StatuseOrderKey"
              },
              {
                "name": "TypeKey"
              },
              {
                "name": "Payment%"
              }
            ],
            "measures": [
              {
                "name": "Sales Total"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "User",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "DimCompany",
            "filterExpression": "[Companykey]=3"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}