{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/hyperv-srv;DataWarehouse",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "hyperv-srv",
            "database": "DataWarehouse"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "InventTranceKey",
            "dataType": "string",
            "sourceColumn": "InventTranceKey"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "sourceColumn": "UnitKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "StatusKey",
            "dataType": "int64",
            "sourceColumn": "StatusKey"
          },
          {
            "name": "TypeKey",
            "dataType": "int64",
            "sourceColumn": "TypeKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "sourceColumn": "CarKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodDeliverykey",
            "dataType": "int64",
            "sourceColumn": "MethodDeliverykey"
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "sourceColumn": "PaymentMethodKey"
          },
          {
            "name": "OrderDateAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "OrderDateAlternativeKey"
          },
          {
            "name": "ProductionDateAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "ProductionDateAlternativeKey"
          },
          {
            "name": "ShippingDateAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "ShippingDateAlternativeKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "double",
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate"
          },
          {
            "name": "ProductionDate",
            "dataType": "dateTime",
            "sourceColumn": "ProductionDate"
          },
          {
            "name": "ShippingDate",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate"
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "SalesQty",
            "dataType": "double",
            "sourceColumn": "SalesQty"
          },
          {
            "name": "DiscountPercent",
            "dataType": "double",
            "sourceColumn": "DiscountPercent"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "sourceColumn": "LineAmount"
          },
          {
            "name": "AmountAfterTax",
            "dataType": "double",
            "sourceColumn": "AmountAfterTax"
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "sourceColumn": "TaxAmount"
          },
          {
            "name": "Payment",
            "dataType": "double",
            "sourceColumn": "Payment"
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "sourceColumn": "LastupdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactSales, each true)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Line Amount",
            "expression": "ROUND(sum(FactSales[LineAmount]),0)"
          },
          {
            "name": "Total Amount",
            "description": "Total Amount After Tax",
            "expression": "round(sum(FactSales[AmountAfterTax]),0)"
          },
          {
            "name": "Tax Amount",
            "expression": "round(sum(FactSales[TaxAmount]),0)"
          },
          {
            "name": "Total Payment",
            "expression": "round(sum(FactSales[Payment]),0)"
          },
          {
            "name": "Count SO",
            "expression": "DISTINCTCOUNT(FactSales[SalesOrderNumber])"
          },
          {
            "name": "Unit Price",
            "expression": "ROUND(sum(FactSales[UnitPrice]),0)"
          },
          {
            "name": "Sales Qty",
            "expression": "sum(FactSales[SalesQty])"
          }
        ]
      },
      {
        "name": "DimBranche",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "BrancheAlternativeKey",
            "dataType": "string",
            "sourceColumn": "BrancheAlternativeKey"
          },
          {
            "name": "BrancheName",
            "dataType": "string",
            "sourceColumn": "BrancheName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimBranche = Source{[Schema=\"dbo\",Item=\"DimBranche\"]}[Data]",
                "in",
                "    dbo_DimBranche"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCar",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "sourceColumn": "CarKey"
          },
          {
            "name": "CarAlternativeKey",
            "dataType": "string",
            "sourceColumn": "CarAlternativeKey"
          },
          {
            "name": "CarNumber",
            "dataType": "string",
            "sourceColumn": "CarNumber"
          },
          {
            "name": "CarName",
            "dataType": "string",
            "sourceColumn": "CarName"
          },
          {
            "name": "CarType",
            "dataType": "int64",
            "sourceColumn": "CarType"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCar = Source{[Schema=\"dbo\",Item=\"DimCar\"]}[Data]",
                "in",
                "    dbo_DimCar"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCompany",
        "columns": [
          {
            "name": "Companykey",
            "dataType": "int64",
            "sourceColumn": "Companykey"
          },
          {
            "name": "CompanyAlternativeKey",
            "dataType": "string",
            "sourceColumn": "CompanyAlternativeKey"
          },
          {
            "name": "CompanyName",
            "dataType": "string",
            "sourceColumn": "CompanyName"
          },
          {
            "name": "Desc",
            "dataType": "string",
            "sourceColumn": "Desc"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCompany = Source{[Schema=\"dbo\",Item=\"DimCompany\"]}[Data]",
                "in",
                "    dbo_DimCompany"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "CustomerAlternativeKey",
            "dataType": "string",
            "sourceColumn": "CustomerAlternativeKey"
          },
          {
            "name": "CustomerName",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "CustomerGroup",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "CustomerType",
            "dataType": "string",
            "sourceColumn": "CustomerType"
          },
          {
            "name": "CustomerClassification",
            "dataType": "string",
            "sourceColumn": "CustomerClassification"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "FullDate",
            "dataType": "string",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeek",
            "dataType": "string",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "string",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "string",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "string",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "string",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "string",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "Season",
            "dataType": "string",
            "sourceColumn": "Season"
          },
          {
            "name": "Semester",
            "dataType": "string",
            "sourceColumn": "Semester"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDimension",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "DimensionAlternativeKey",
            "dataType": "string",
            "sourceColumn": "DimensionAlternativeKey"
          },
          {
            "name": "InventLocationId",
            "dataType": "string",
            "sourceColumn": "InventLocationId"
          },
          {
            "name": "WarehouseName",
            "dataType": "string",
            "sourceColumn": "WarehouseName"
          },
          {
            "name": "SiteName",
            "dataType": "string",
            "sourceColumn": "SiteName"
          },
          {
            "name": "ColorName",
            "dataType": "string",
            "sourceColumn": "ColorName"
          },
          {
            "name": "SizeName",
            "dataType": "string",
            "sourceColumn": "SizeName"
          },
          {
            "name": "ConfigrationName",
            "dataType": "string",
            "sourceColumn": "ConfigrationName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDimension = Source{[Schema=\"dbo\",Item=\"DimDimension\"]}[Data]",
                "in",
                "    dbo_DimDimension"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "EmployeeAlternativeKey",
            "dataType": "string",
            "sourceColumn": "EmployeeAlternativeKey"
          },
          {
            "name": "EmployeeName",
            "dataType": "string",
            "sourceColumn": "EmployeeName"
          },
          {
            "name": "Job",
            "dataType": "string",
            "sourceColumn": "Job"
          },
          {
            "name": "DepartmenName",
            "dataType": "string",
            "sourceColumn": "DepartmenName"
          },
          {
            "name": "DivisionName",
            "dataType": "string",
            "sourceColumn": "DivisionName"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "ContractType",
            "dataType": "string",
            "sourceColumn": "ContractType"
          },
          {
            "name": "ContractDate",
            "dataType": "dateTime",
            "sourceColumn": "ContractDate"
          },
          {
            "name": "ContractEndDate",
            "dataType": "dateTime",
            "sourceColumn": "ContractEndDate"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "HireDate",
            "dataType": "dateTime",
            "sourceColumn": "HireDate"
          },
          {
            "name": "InsuranceDate",
            "dataType": "dateTime",
            "sourceColumn": "InsuranceDate"
          },
          {
            "name": "WorkeStatus",
            "dataType": "string",
            "sourceColumn": "WorkeStatus"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    dbo_DimEmployee"
              ]
            }
          }
        ]
      },
      {
        "name": "DimFixOrderStatus",
        "columns": [
          {
            "name": "StatusKey",
            "dataType": "int64",
            "sourceColumn": "StatusKey"
          },
          {
            "name": "StatusName",
            "dataType": "string",
            "sourceColumn": "StatusName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixOrderStatus = Source{[Schema=\"dbo\",Item=\"DimFixOrderStatus\"]}[Data]",
                "in",
                "    dbo_DimFixOrderStatus"
              ]
            }
          }
        ]
      },
      {
        "name": "DimFixSalesType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "sourceColumn": "TypeKey"
          },
          {
            "name": "TypeName",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixSalesType = Source{[Schema=\"dbo\",Item=\"DimFixSalesType\"]}[Data]",
                "in",
                "    dbo_DimFixSalesType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "GeographyAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "GeographyAlternativeKey"
          },
          {
            "name": "RegionName",
            "dataType": "string",
            "sourceColumn": "RegionName"
          },
          {
            "name": "StateName",
            "dataType": "string",
            "sourceColumn": "StateName"
          },
          {
            "name": "CityName",
            "dataType": "string",
            "sourceColumn": "CityName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                "in",
                "    dbo_DimGeography"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodAcquisition",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodAcquisitionAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "MethodAcquisitionAlternativeKey"
          },
          {
            "name": "NameMethodAcquisition",
            "dataType": "string",
            "sourceColumn": "NameMethodAcquisition"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodAcquisition = Source{[Schema=\"dbo\",Item=\"DimMethodAcquisition\"]}[Data]",
                "in",
                "    dbo_DimMethodAcquisition"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodDelivery",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodDeliveryKey",
            "dataType": "int64",
            "sourceColumn": "MethodDeliveryKey"
          },
          {
            "name": "MethodDeliveryAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "MethodDeliveryAlternativeKey"
          },
          {
            "name": "NameMethodDelivery",
            "dataType": "string",
            "sourceColumn": "NameMethodDelivery"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodDelivery = Source{[Schema=\"dbo\",Item=\"DimMethodDelivery\"]}[Data]",
                "in",
                "    dbo_DimMethodDelivery"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodPayment",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodPaymentKey",
            "dataType": "int64",
            "sourceColumn": "MethodPaymentKey"
          },
          {
            "name": "MethodPaymentAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "MethodPaymentAlternativeKey"
          },
          {
            "name": "NameMethodsPayment",
            "dataType": "string",
            "sourceColumn": "NameMethodsPayment"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodPayment = Source{[Schema=\"dbo\",Item=\"DimMethodPayment\"]}[Data]",
                "in",
                "    dbo_DimMethodPayment"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternativeKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternativeKey"
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "SubCategory",
            "dataType": "string",
            "sourceColumn": "SubCategory"
          },
          {
            "name": "StatusCategory",
            "dataType": "string",
            "sourceColumn": "StatusCategory"
          },
          {
            "name": "StatusProduct",
            "dataType": "string",
            "sourceColumn": "StatusProduct"
          },
          {
            "name": "GroupType",
            "dataType": "string",
            "sourceColumn": "GroupType"
          },
          {
            "name": "SalesPrice",
            "dataType": "decimal",
            "sourceColumn": "SalesPrice"
          },
          {
            "name": "PurchasePrice",
            "dataType": "decimal",
            "sourceColumn": "PurchasePrice"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "boolean",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ]
      },
      {
        "name": "DimPromotion",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "PromotionAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "PromotionAlternativeKey"
          },
          {
            "name": "STATUS",
            "dataType": "int64",
            "sourceColumn": "STATUS"
          },
          {
            "name": "FROMDATE",
            "dataType": "dateTime",
            "sourceColumn": "FROMDATE"
          },
          {
            "name": "TODATE",
            "dataType": "dateTime",
            "sourceColumn": "TODATE"
          },
          {
            "name": "DELIVERYDATE",
            "dataType": "dateTime",
            "sourceColumn": "DELIVERYDATE"
          },
          {
            "name": "DESCRIPTION",
            "dataType": "string",
            "sourceColumn": "DESCRIPTION"
          },
          {
            "name": "ITEMGROUP",
            "dataType": "string",
            "sourceColumn": "ITEMGROUP"
          },
          {
            "name": "DESCACTIVE",
            "dataType": "int64",
            "sourceColumn": "DESCACTIVE"
          },
          {
            "name": "SORTDISC",
            "dataType": "int64",
            "sourceColumn": "SORTDISC"
          },
          {
            "name": "PRICEDISCOUNT",
            "dataType": "decimal",
            "sourceColumn": "PRICEDISCOUNT"
          },
          {
            "name": "DISCOUNT",
            "dataType": "double",
            "sourceColumn": "DISCOUNT"
          },
          {
            "name": "QUANTITY",
            "dataType": "int64",
            "sourceColumn": "QUANTITY"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimPromotion = Source{[Schema=\"dbo\",Item=\"DimPromotion\"]}[Data]",
                "in",
                "    dbo_DimPromotion"
              ]
            }
          }
        ]
      },
      {
        "name": "DimUnit",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "sourceColumn": "UnitKey"
          },
          {
            "name": "UnitAlternativeKey",
            "dataType": "string",
            "sourceColumn": "UnitAlternativeKey"
          },
          {
            "name": "UnitName",
            "dataType": "string",
            "sourceColumn": "UnitName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimUnit = Source{[Schema=\"dbo\",Item=\"DimUnit\"]}[Data]",
                "in",
                "    dbo_DimUnit"
              ]
            }
          }
        ]
      },
      {
        "name": "FactSalesCommission",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "SalesCommissionKey",
            "dataType": "int64",
            "sourceColumn": "SalesCommissionKey"
          },
          {
            "name": "SalesCommissionAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "SalesCommissionAlternativeKey"
          },
          {
            "name": "TargetLevelkey",
            "dataType": "int64",
            "sourceColumn": "TargetLevelkey"
          },
          {
            "name": "EmpTypeKey",
            "dataType": "int64",
            "sourceColumn": "EmpTypeKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "SalesCommissionDateAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "SalesCommissionDateAlternativeKey"
          },
          {
            "name": "SalesCommissionDate",
            "dataType": "dateTime",
            "sourceColumn": "SalesCommissionDateKey"
          },
          {
            "name": "Precent",
            "dataType": "double",
            "sourceColumn": "Precent"
          },
          {
            "name": "AmountFrom",
            "dataType": "double",
            "sourceColumn": "AmountFrom"
          },
          {
            "name": "AmountTo",
            "dataType": "double",
            "sourceColumn": "AmountTo"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "Amount"
          },
          {
            "name": "TotalSales",
            "dataType": "double",
            "sourceColumn": "TotalSales"
          },
          {
            "name": "CountSo",
            "dataType": "int64",
            "sourceColumn": "CountSo"
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "sourceColumn": "LastupdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSalesCommission = Source{[Schema=\"dbo\",Item=\"FactSalesCommission\"]}[Data]",
                "in",
                "    dbo_FactSalesCommission"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Commission Amount",
            "expression": "sum(FactSalesCommission[Amount])"
          },
          {
            "name": "Total Sales",
            "expression": "sum(FactSalesCommission[TotalSales])"
          },
          {
            "name": "Order Count",
            "expression": "SUM((FactSalesCommission[CountSo]))"
          }
        ]
      },
      {
        "name": "DimEmpType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "sourceColumn": "TypeKey"
          },
          {
            "name": "TypeName",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmpType = Source{[Schema=\"dbo\",Item=\"DimEmpType\"]}[Data]",
                "in",
                "    dbo_DimEmpType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimTargetLevel",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "TargetLevelKey",
            "dataType": "int64",
            "sourceColumn": "TargetLevelKey"
          },
          {
            "name": "DgreeName",
            "dataType": "string",
            "sourceColumn": "DgreeName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimTargetLevel = Source{[Schema=\"dbo\",Item=\"DimTargetLevel\"]}[Data]",
                "in",
                "    dbo_DimTargetLevel"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "6e4cc0e1-4a2c-4b92-9bb6-b8ca2e3343ac",
        "fromTable": "FactSales",
        "fromColumn": "OrderDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "af968cfa-45fd-4094-ad2d-2299ec614368",
        "fromTable": "FactSales",
        "fromColumn": "ProductionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "c8e34e60-1984-43d6-8ac4-d580c99dfb5d",
        "fromTable": "FactSales",
        "fromColumn": "ShippingDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "efcc7883-a565-4dfd-9a51-1b3ee580e8a7",
        "fromTable": "FactSales",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "20a4f5a8-dc1b-425c-b945-32227fcfc412",
        "fromTable": "FactSales",
        "fromColumn": "StatusKey",
        "toTable": "DimFixOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "6f52df78-743c-42be-9b14-6b7827a890b0",
        "fromTable": "FactSales",
        "fromColumn": "TypeKey",
        "toTable": "DimFixSalesType",
        "toColumn": "TypeKey"
      },
      {
        "name": "79e6227d-31ad-4900-8d34-b33b2afe9fce",
        "fromTable": "FactSales",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "BrancheKey"
      },
      {
        "name": "a8a9a89f-90b1-4ebc-9808-8437e634cfe2",
        "fromTable": "FactSales",
        "fromColumn": "CarKey",
        "toTable": "DimCar",
        "toColumn": "CarKey"
      },
      {
        "name": "671e7041-af90-4534-9e1d-bf70eee94922",
        "fromTable": "FactSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "75b87e4a-c9f4-4381-a2a8-f1fa8687c0fe",
        "fromTable": "FactSales",
        "fromColumn": "DimensionKey",
        "toTable": "DimDimension",
        "toColumn": "DimensionKey"
      },
      {
        "name": "081c882e-a615-4c92-97e5-0d90b34e3524",
        "fromTable": "FactSales",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "7bfbef40-1be6-47d8-b553-00605b9e71fe",
        "fromTable": "FactSales",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "5abc277d-ce70-4f78-996a-190d3de74032",
        "fromTable": "FactSales",
        "fromColumn": "MethodAcquisitionKey",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "d223a52a-cb58-44b7-ae13-70135d56570b",
        "fromTable": "FactSales",
        "fromColumn": "MethodDeliverykey",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "934f097e-9a0a-4860-838e-901584f6065f",
        "fromTable": "FactSales",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "9c161b3d-7507-4639-a51f-72b0560714aa",
        "fromTable": "FactSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "6d62c46f-4e0d-48d7-a479-b881f40f845c",
        "fromTable": "FactSales",
        "fromColumn": "PromotionKey",
        "toTable": "DimPromotion",
        "toColumn": "PromotionKey"
      },
      {
        "name": "e3cc56e2-90e5-427f-9b93-d04099174991",
        "fromTable": "FactSales",
        "fromColumn": "UnitKey",
        "toTable": "DimUnit",
        "toColumn": "UnitKey"
      },
      {
        "name": "6096f752-d7ad-43b2-bde0-a91d46ba73e7",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmpTypeKey",
        "toTable": "DimEmpType",
        "toColumn": "TypeKey"
      },
      {
        "name": "5fd05464-465a-4574-a948-0a62237090fb",
        "fromTable": "FactSalesCommission",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "BrancheKey"
      },
      {
        "name": "817836f0-cea8-4f33-9f20-33104c3c08d9",
        "fromTable": "FactSalesCommission",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "73658ad8-63de-4d26-86ef-768212a97b81",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "10aa843d-d7f6-4025-b725-a92daa842154",
        "fromTable": "FactSalesCommission",
        "fromColumn": "SalesCommissionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "c88dc798-0227-47cb-8acb-18655deedb88",
        "fromTable": "FactSalesCommission",
        "fromColumn": "TargetLevelkey",
        "toTable": "DimTargetLevel",
        "toColumn": "TargetLevelKey"
      }
    ],
    "perspectives": [
      {
        "name": "Sales",
        "tables": [
          {
            "name": "DimBranche",
            "columns": [
              {
                "name": "BrancheName"
              }
            ]
          },
          {
            "name": "DimCar",
            "columns": [
              {
                "name": "CarName"
              }
            ]
          },
          {
            "name": "DimCompany",
            "columns": [
              {
                "name": "CompanyName"
              }
            ]
          },
          {
            "name": "DimCustomer",
            "columns": [
              {
                "name": "Birthday"
              },
              {
                "name": "CustomerClassification"
              },
              {
                "name": "CustomerGroup"
              },
              {
                "name": "CustomerName"
              },
              {
                "name": "CustomerType"
              },
              {
                "name": "Gender"
              }
            ]
          },
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayName"
              },
              {
                "name": "DayOfMonth"
              },
              {
                "name": "DayOfQuarter"
              },
              {
                "name": "DayOfWeek"
              },
              {
                "name": "DayOfWeekInMonth"
              },
              {
                "name": "DayOfWeekInYear"
              },
              {
                "name": "DayOfYear"
              },
              {
                "name": "DaySuffix"
              },
              {
                "name": "FirstDayOfMonth"
              },
              {
                "name": "FirstDayOfQuarter"
              },
              {
                "name": "FirstDayOfYear"
              },
              {
                "name": "FullDate"
              },
              {
                "name": "HolidayName"
              },
              {
                "name": "IsHoliday"
              },
              {
                "name": "LastDayOfMonth"
              },
              {
                "name": "LastDayOfQuarter"
              },
              {
                "name": "LastDayOfYear"
              },
              {
                "name": "MMYYYY"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "MonthOfQuarter"
              },
              {
                "name": "MonthYear"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "QuarterName"
              },
              {
                "name": "Season"
              },
              {
                "name": "Semester"
              },
              {
                "name": "WeekOfMonth"
              },
              {
                "name": "WeekOfQuarter"
              },
              {
                "name": "WeekOfYear"
              },
              {
                "name": "Year"
              },
              {
                "name": "YearName"
              }
            ]
          },
          {
            "name": "DimDimension",
            "columns": [
              {
                "name": "ColorName"
              },
              {
                "name": "ConfigrationName"
              },
              {
                "name": "SiteName"
              },
              {
                "name": "SizeName"
              },
              {
                "name": "WarehouseName"
              }
            ]
          },
          {
            "name": "DimEmployee",
            "columns": [
              {
                "name": "BirthDate"
              },
              {
                "name": "DepartmenName"
              },
              {
                "name": "DivisionName"
              },
              {
                "name": "EmployeeName"
              },
              {
                "name": "Gender"
              },
              {
                "name": "HireDate"
              },
              {
                "name": "Job"
              },
              {
                "name": "WorkeStatus"
              }
            ]
          },
          {
            "name": "DimFixOrderStatus",
            "columns": [
              {
                "name": "StatusName"
              }
            ]
          },
          {
            "name": "DimFixSalesType",
            "columns": [
              {
                "name": "TypeName"
              }
            ]
          },
          {
            "name": "DimGeography",
            "columns": [
              {
                "name": "CityName"
              },
              {
                "name": "RegionName"
              },
              {
                "name": "StateName"
              }
            ]
          },
          {
            "name": "DimMethodAcquisition",
            "columns": [
              {
                "name": "NameMethodAcquisition"
              }
            ]
          },
          {
            "name": "DimMethodDelivery",
            "columns": [
              {
                "name": "NameMethodDelivery"
              }
            ]
          },
          {
            "name": "DimMethodPayment",
            "columns": [
              {
                "name": "NameMethodsPayment"
              }
            ]
          },
          {
            "name": "DimProduct",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "GroupType"
              },
              {
                "name": "ProductName"
              },
              {
                "name": "PurchasePrice"
              },
              {
                "name": "SalesPrice"
              },
              {
                "name": "StatusCategory"
              },
              {
                "name": "StatusProduct"
              },
              {
                "name": "SubCategory"
              }
            ]
          },
          {
            "name": "DimPromotion",
            "columns": [
              {
                "name": "DELIVERYDATE"
              },
              {
                "name": "DESCACTIVE"
              },
              {
                "name": "DESCRIPTION"
              },
              {
                "name": "DISCOUNT"
              },
              {
                "name": "FROMDATE"
              },
              {
                "name": "ITEMGROUP"
              },
              {
                "name": "Location"
              },
              {
                "name": "PRICEDISCOUNT"
              },
              {
                "name": "QUANTITY"
              },
              {
                "name": "SORTDISC"
              },
              {
                "name": "STATUS"
              },
              {
                "name": "TODATE"
              }
            ]
          },
          {
            "name": "DimTargetLevel",
            "columns": [
              {
                "name": "DgreeName"
              }
            ]
          },
          {
            "name": "DimUnit",
            "columns": [
              {
                "name": "UnitName"
              }
            ]
          },
          {
            "name": "FactSales",
            "columns": [
              {
                "name": "OrderDate"
              },
              {
                "name": "SalesOrderNumber"
              },
              {
                "name": "ProductionDate"
              },
              {
                "name": "ShippingDate"
              }
            ],
            "measures": [
              {
                "name": "Total Amount"
              },
              {
                "name": "Count SO"
              },
              {
                "name": "Line Amount"
              },
              {
                "name": "Tax Amount"
              },
              {
                "name": "Total Payment"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Sales Qty"
              }
            ]
          }
        ]
      },
      {
        "name": "SalesCommission",
        "tables": [
          {
            "name": "DimBranche",
            "columns": [
              {
                "name": "BrancheName"
              }
            ]
          },
          {
            "name": "DimCompany",
            "columns": [
              {
                "name": "CompanyName"
              }
            ]
          },
          {
            "name": "DimDate",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "DayName"
              },
              {
                "name": "DayOfMonth"
              },
              {
                "name": "DayOfQuarter"
              },
              {
                "name": "DayOfWeek"
              },
              {
                "name": "DayOfWeekInMonth"
              },
              {
                "name": "DayOfWeekInYear"
              },
              {
                "name": "DayOfYear"
              },
              {
                "name": "DaySuffix"
              },
              {
                "name": "FirstDayOfMonth"
              },
              {
                "name": "FirstDayOfQuarter"
              },
              {
                "name": "FirstDayOfYear"
              },
              {
                "name": "FullDate"
              },
              {
                "name": "HolidayName"
              },
              {
                "name": "IsHoliday"
              },
              {
                "name": "LastDayOfMonth"
              },
              {
                "name": "LastDayOfQuarter"
              },
              {
                "name": "LastDayOfYear"
              },
              {
                "name": "MMYYYY"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "MonthOfQuarter"
              },
              {
                "name": "MonthYear"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "QuarterName"
              },
              {
                "name": "Season"
              },
              {
                "name": "Semester"
              },
              {
                "name": "WeekOfMonth"
              },
              {
                "name": "WeekOfQuarter"
              },
              {
                "name": "WeekOfYear"
              },
              {
                "name": "Year"
              },
              {
                "name": "YearName"
              }
            ]
          },
          {
            "name": "DimEmployee",
            "columns": [
              {
                "name": "BirthDate"
              },
              {
                "name": "DepartmenName"
              },
              {
                "name": "EmployeeName"
              },
              {
                "name": "Gender"
              },
              {
                "name": "Job"
              }
            ]
          },
          {
            "name": "DimEmpType",
            "columns": [
              {
                "name": "TypeName"
              }
            ]
          },
          {
            "name": "DimTargetLevel",
            "columns": [
              {
                "name": "DgreeName"
              }
            ]
          },
          {
            "name": "FactSalesCommission",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "SalesCommissionDate"
              },
              {
                "name": "SalesCommissionKey"
              },
              {
                "name": "EmpTypeKey"
              }
            ],
            "measures": [
              {
                "name": "Commission Amount"
              },
              {
                "name": "Total Sales"
              },
              {
                "name": "Order Count"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "SalesCommission",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "MFFCO\\SBD05",
            "memberId": "S-1-5-21-1912877164-1294261322-872667718-159603"
          }
        ],
        "tablePermissions": [
          {
            "name": "DimCompany",
            "filterExpression": "[Companykey]=3",
            "metadataPermission": "none"
          },
          {
            "name": "DimTargetLevel",
            "metadataPermission": "none"
          },
          {
            "name": "FactSalesCommission",
            "metadataPermission": "none"
          },
          {
            "name": "DimEmployee",
            "metadataPermission": "none"
          },
          {
            "name": "DimDate",
            "metadataPermission": "none"
          },
          {
            "name": "DimBranche",
            "metadataPermission": "none"
          },
          {
            "name": "DimEmpType",
            "metadataPermission": "none"
          }
        ]
      },
      {
        "name": "Admin",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "MFFCO\\ism01",
            "memberId": "S-1-5-21-1912877164-1294261322-872667718-2682"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}