{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/hyperv-srv;DataWarehouse",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "mffco-srv",
            "database": "DataWarehouse"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "InventTranceKey",
            "dataType": "string",
            "sourceColumn": "InventTranceKey"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "UnitKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusKey"
          },
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CarKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodDeliverykey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliverykey"
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey"
          },
          {
            "name": "OrderDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateAlternativeKey"
          },
          {
            "name": "ProductionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductionDateAlternativeKey"
          },
          {
            "name": "ShippingDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippingDateAlternativeKey"
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "ProductionDate",
            "dataType": "dateTime",
            "sourceColumn": "ProductionDate",
            "formatString": "dd-MM-yyyy"
          },
          {
            "name": "ShippingDate",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "UnitPrice",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "SalesQty",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesQty"
          },
          {
            "name": "DiscountPercent",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountPercent"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LineAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "AmountAfterTax",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountAfterTax",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Payment",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Payment",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactSales, each true)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Line Amount",
            "expression": "ROUND(sum(FactSales[LineAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Amount",
            "description": "Total Amount After Tax",
            "expression": "round(sum(FactSales[AmountAfterTax]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Tax Amount",
            "expression": "round(sum(FactSales[TaxAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Payment",
            "expression": "round(sum(FactSales[Payment]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count SO",
            "expression": "DISTINCTCOUNT(FactSales[SalesOrderNumber])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Unit Price",
            "expression": "ROUND(sum(FactSales[UnitPrice]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sales Qty",
            "expression": "sum(FactSales[SalesQty])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Percent",
            "expression": "SUM(FactSales[DiscountPercent])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "expression": "SUM(FactSales[DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Amount",
            "expression": "MAX([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Minimum of Discount Amount",
            "expression": "MIN([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Percent",
            "expression": "MAX([DiscountPercent])"
          },
          {
            "name": "Minimum of DiscountPercent",
            "expression": "MIN([DiscountPercent])"
          }
        ]
      },
      {
        "name": "DimCar",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "sourceColumn": "CarKey"
          },
          {
            "name": "CarAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CarAlternativeKey"
          },
          {
            "name": "CarNumber",
            "dataType": "string",
            "sourceColumn": "CarNumber"
          },
          {
            "name": "CarName",
            "dataType": "string",
            "sourceColumn": "CarName"
          },
          {
            "name": "CarType",
            "dataType": "int64",
            "sourceColumn": "CarType"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCar = Source{[Schema=\"dbo\",Item=\"DimCar\"]}[Data]",
                "in",
                "    dbo_DimCar"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCompany",
        "columns": [
          {
            "name": "Companykey",
            "dataType": "int64",
            "sourceColumn": "Companykey"
          },
          {
            "name": "CompanyAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CompanyAlternativeKey"
          },
          {
            "name": "CompanyName",
            "dataType": "string",
            "sourceColumn": "CompanyName"
          },
          {
            "name": "Desc",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Desc"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCompany = Source{[Schema=\"dbo\",Item=\"DimCompany\"]}[Data]",
                "in",
                "    dbo_DimCompany"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "CustomerAlternativeKey",
            "dataType": "string",
            "sourceColumn": "CustomerAlternativeKey"
          },
          {
            "name": "CustomerName",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "CustomerGroup",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "CustomerType",
            "dataType": "string",
            "sourceColumn": "CustomerType"
          },
          {
            "name": "CustomerClassification",
            "dataType": "string",
            "sourceColumn": "CustomerClassification"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDimension",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "DimensionAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DimensionAlternativeKey"
          },
          {
            "name": "InventLocationId",
            "dataType": "string",
            "sourceColumn": "InventLocationId"
          },
          {
            "name": "WarehouseName",
            "dataType": "string",
            "sourceColumn": "WarehouseName"
          },
          {
            "name": "SiteName",
            "dataType": "string",
            "sourceColumn": "SiteName"
          },
          {
            "name": "ColorName",
            "dataType": "string",
            "sourceColumn": "ColorName"
          },
          {
            "name": "SizeName",
            "dataType": "string",
            "sourceColumn": "SizeName"
          },
          {
            "name": "ConfigrationName",
            "dataType": "string",
            "sourceColumn": "ConfigrationName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDimension = Source{[Schema=\"dbo\",Item=\"DimDimension\"]}[Data]",
                "in",
                "    dbo_DimDimension"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "EmployeeAlternativeKey",
            "dataType": "string",
            "sourceColumn": "EmployeeAlternativeKey"
          },
          {
            "name": "EmployeeName",
            "dataType": "string",
            "sourceColumn": "EmployeeName"
          },
          {
            "name": "Job",
            "dataType": "string",
            "sourceColumn": "Job"
          },
          {
            "name": "DepartmenName",
            "dataType": "string",
            "sourceColumn": "DepartmenName"
          },
          {
            "name": "DivisionName",
            "dataType": "string",
            "sourceColumn": "DivisionName"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "ContractType",
            "dataType": "string",
            "sourceColumn": "ContractType"
          },
          {
            "name": "ContractDate",
            "dataType": "dateTime",
            "sourceColumn": "ContractDate"
          },
          {
            "name": "ContractEndDate",
            "dataType": "dateTime",
            "sourceColumn": "ContractEndDate"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "HireDate",
            "dataType": "dateTime",
            "sourceColumn": "HireDate"
          },
          {
            "name": "InsuranceDate",
            "dataType": "dateTime",
            "sourceColumn": "InsuranceDate"
          },
          {
            "name": "WorkeStatus",
            "dataType": "string",
            "sourceColumn": "WorkeStatus"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    dbo_DimEmployee"
              ]
            }
          }
        ]
      },
      {
        "name": "DimFixOrderStatus",
        "columns": [
          {
            "name": "StatusKey",
            "dataType": "int64",
            "sourceColumn": "StatusKey"
          },
          {
            "name": "StatusName",
            "dataType": "string",
            "sourceColumn": "StatusName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixOrderStatus = Source{[Schema=\"dbo\",Item=\"DimFixOrderStatus\"]}[Data]",
                "in",
                "    dbo_DimFixOrderStatus"
              ]
            }
          }
        ]
      },
      {
        "name": "DimFixSalesType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "sourceColumn": "TypeKey"
          },
          {
            "name": "TypeName",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixSalesType = Source{[Schema=\"dbo\",Item=\"DimFixSalesType\"]}[Data]",
                "in",
                "    dbo_DimFixSalesType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "GeographyAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyAlternativeKey"
          },
          {
            "name": "RegionName",
            "dataType": "string",
            "sourceColumn": "RegionName"
          },
          {
            "name": "StateName",
            "dataType": "string",
            "sourceColumn": "StateName"
          },
          {
            "name": "CityName",
            "dataType": "string",
            "sourceColumn": "CityName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                "in",
                "    dbo_DimGeography"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyGeography",
            "levels": [
              {
                "name": "RegionName",
                "ordinal": 0,
                "column": "RegionName"
              },
              {
                "name": "StateName",
                "ordinal": 1,
                "column": "StateName"
              },
              {
                "name": "CityName",
                "ordinal": 2,
                "column": "CityName"
              }
            ]
          }
        ]
      },
      {
        "name": "DimMethodAcquisition",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodAcquisitionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionAlternativeKey"
          },
          {
            "name": "NameMethodAcquisition",
            "dataType": "string",
            "sourceColumn": "NameMethodAcquisition"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodAcquisition = Source{[Schema=\"dbo\",Item=\"DimMethodAcquisition\"]}[Data]",
                "in",
                "    dbo_DimMethodAcquisition"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodDelivery",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodDeliveryKey",
            "dataType": "int64",
            "sourceColumn": "MethodDeliveryKey"
          },
          {
            "name": "MethodDeliveryAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliveryAlternativeKey"
          },
          {
            "name": "NameMethodDelivery",
            "dataType": "string",
            "sourceColumn": "NameMethodDelivery"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodDelivery = Source{[Schema=\"dbo\",Item=\"DimMethodDelivery\"]}[Data]",
                "in",
                "    dbo_DimMethodDelivery"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodPayment",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodPaymentKey",
            "dataType": "int64",
            "sourceColumn": "MethodPaymentKey"
          },
          {
            "name": "MethodPaymentAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodPaymentAlternativeKey"
          },
          {
            "name": "NameMethodsPayment",
            "dataType": "string",
            "sourceColumn": "NameMethodsPayment"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodPayment = Source{[Schema=\"dbo\",Item=\"DimMethodPayment\"]}[Data]",
                "in",
                "    dbo_DimMethodPayment"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternativeKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternativeKey"
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "SubCategory",
            "dataType": "string",
            "sourceColumn": "SubCategory"
          },
          {
            "name": "StatusCategory",
            "dataType": "string",
            "sourceColumn": "StatusCategory"
          },
          {
            "name": "StatusProduct",
            "dataType": "string",
            "sourceColumn": "StatusProduct"
          },
          {
            "name": "GroupType",
            "dataType": "string",
            "sourceColumn": "GroupType"
          },
          {
            "name": "SalesPrice",
            "dataType": "decimal",
            "sourceColumn": "SalesPrice"
          },
          {
            "name": "PurchasePrice",
            "dataType": "decimal",
            "sourceColumn": "PurchasePrice"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "boolean",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ]
      },
      {
        "name": "DimPromotion",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "PromotionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionAlternativeKey"
          },
          {
            "name": "STATUS",
            "dataType": "int64",
            "sourceColumn": "STATUS"
          },
          {
            "name": "FROMDATE",
            "dataType": "dateTime",
            "sourceColumn": "FROMDATE"
          },
          {
            "name": "TODATE",
            "dataType": "dateTime",
            "sourceColumn": "TODATE"
          },
          {
            "name": "DELIVERYDATE",
            "dataType": "dateTime",
            "sourceColumn": "DELIVERYDATE"
          },
          {
            "name": "DESCRIPTION",
            "dataType": "string",
            "sourceColumn": "DESCRIPTION"
          },
          {
            "name": "ITEMGROUP",
            "dataType": "string",
            "sourceColumn": "ITEMGROUP"
          },
          {
            "name": "DESCACTIVE",
            "dataType": "int64",
            "sourceColumn": "DESCACTIVE"
          },
          {
            "name": "SORTDISC",
            "dataType": "int64",
            "sourceColumn": "SORTDISC"
          },
          {
            "name": "PRICEDISCOUNT",
            "dataType": "decimal",
            "sourceColumn": "PRICEDISCOUNT"
          },
          {
            "name": "DISCOUNT",
            "dataType": "double",
            "sourceColumn": "DISCOUNT"
          },
          {
            "name": "QUANTITY",
            "dataType": "int64",
            "sourceColumn": "QUANTITY"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimPromotion = Source{[Schema=\"dbo\",Item=\"DimPromotion\"]}[Data]",
                "in",
                "    dbo_DimPromotion"
              ]
            }
          }
        ]
      },
      {
        "name": "DimUnit",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "sourceColumn": "UnitKey"
          },
          {
            "name": "UnitAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "UnitAlternativeKey"
          },
          {
            "name": "UnitName",
            "dataType": "string",
            "sourceColumn": "UnitName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimUnit = Source{[Schema=\"dbo\",Item=\"DimUnit\"]}[Data]",
                "in",
                "    dbo_DimUnit"
              ]
            }
          }
        ]
      },
      {
        "name": "DimBranche",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "BrancheAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BrancheAlternativeKey"
          },
          {
            "name": "BrancheName",
            "dataType": "string",
            "sourceColumn": "BrancheName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimBranche = Source{[Schema=\"dbo\",Item=\"DimBranche\"]}[Data]",
                "in",
                "    dbo_DimBranche"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "dd-MM-yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"dd-MM-yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "FullDate",
            "dataType": "string",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DayOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "int64",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "int64",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "int64",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "Season",
            "dataType": "string",
            "sourceColumn": "Season"
          },
          {
            "name": "Semester",
            "dataType": "string",
            "sourceColumn": "Semester"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyDate",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "DayOfMonth"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "efcc7883-a565-4dfd-9a51-1b3ee580e8a7",
        "fromTable": "FactSales",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "20a4f5a8-dc1b-425c-b945-32227fcfc412",
        "fromTable": "FactSales",
        "fromColumn": "StatusKey",
        "toTable": "DimFixOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "6f52df78-743c-42be-9b14-6b7827a890b0",
        "fromTable": "FactSales",
        "fromColumn": "TypeKey",
        "toTable": "DimFixSalesType",
        "toColumn": "TypeKey"
      },
      {
        "name": "a8a9a89f-90b1-4ebc-9808-8437e634cfe2",
        "fromTable": "FactSales",
        "fromColumn": "CarKey",
        "toTable": "DimCar",
        "toColumn": "CarKey"
      },
      {
        "name": "671e7041-af90-4534-9e1d-bf70eee94922",
        "fromTable": "FactSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "75b87e4a-c9f4-4381-a2a8-f1fa8687c0fe",
        "fromTable": "FactSales",
        "fromColumn": "DimensionKey",
        "toTable": "DimDimension",
        "toColumn": "DimensionKey"
      },
      {
        "name": "081c882e-a615-4c92-97e5-0d90b34e3524",
        "fromTable": "FactSales",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "7bfbef40-1be6-47d8-b553-00605b9e71fe",
        "fromTable": "FactSales",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "5abc277d-ce70-4f78-996a-190d3de74032",
        "fromTable": "FactSales",
        "fromColumn": "MethodAcquisitionKey",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "d223a52a-cb58-44b7-ae13-70135d56570b",
        "fromTable": "FactSales",
        "fromColumn": "MethodDeliverykey",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "934f097e-9a0a-4860-838e-901584f6065f",
        "fromTable": "FactSales",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "9c161b3d-7507-4639-a51f-72b0560714aa",
        "fromTable": "FactSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "6d62c46f-4e0d-48d7-a479-b881f40f845c",
        "fromTable": "FactSales",
        "fromColumn": "PromotionKey",
        "toTable": "DimPromotion",
        "toColumn": "PromotionKey"
      },
      {
        "name": "a6c99fd9-5295-4781-9f3c-11d58f62b6cc",
        "fromTable": "FactSales",
        "fromColumn": "UnitKey",
        "toTable": "DimUnit",
        "toColumn": "UnitKey"
      },
      {
        "name": "88ffaa6a-2caf-46f6-b43e-8544725699d2",
        "fromTable": "FactSales",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "BrancheKey"
      },
      {
        "name": "c4fd38a7-8477-4bac-8505-702a11a9ba54",
        "fromTable": "FactSales",
        "fromColumn": "ProductionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "a34a0957-168b-4eef-9dac-64692bcac096",
        "fromTable": "FactSales",
        "fromColumn": "ShippingDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "b862e642-d68d-4d26-83ad-2f444abcf77b",
        "fromTable": "FactSales",
        "fromColumn": "OrderDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      }
    ],
    "roles": [
      {
        "name": "User",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "DimCompany",
            "filterExpression": "[Companykey]=3"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}