{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/hyperv-srv;DataWarehouse",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "mffco-srv",
            "database": "DataWarehouse"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "Invent Trance Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "InventTranceKey"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "UnitKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusKey"
          },
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CarKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodDeliverykey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliverykey"
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey"
          },
          {
            "name": "OrderDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateAlternativeKey"
          },
          {
            "name": "ProductionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductionDateAlternativeKey"
          },
          {
            "name": "ShippingDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippingDateAlternativeKey"
          },
          {
            "name": "Sales Order",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Short Date",
            "displayFolder": "Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "sourceColumn": "ProductionDate",
            "formatString": "dd-MM-yyyy",
            "displayFolder": "Date"
          },
          {
            "name": "Shipping Date",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate",
            "formatString": "Short Date",
            "displayFolder": "Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "UnitPrice",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "SalesQty",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesQty"
          },
          {
            "name": "DiscountPercent",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountPercent"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LineAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "AmountAfterTax",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountAfterTax",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Payment",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Payment",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          },
          {
            "name": "Create Date Time",
            "dataType": "dateTime",
            "sourceColumn": "CreateDateTime",
            "displayFolder": "Date"
          },
          {
            "name": "StatusOrderKey",
            "dataType": "int64",
            "sourceColumn": "StatusOrderKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactSales, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Line Amount",
            "expression": "ROUND(sum(FactSales[LineAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Amount",
            "description": "Total Amount After Tax",
            "expression": "round(sum(FactSales[AmountAfterTax]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Tax Amount",
            "expression": "round(sum(FactSales[TaxAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Payment",
            "expression": "round(sum(FactSales[Payment]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of SO",
            "expression": "DISTINCTCOUNT(FactSales[Sales Order])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Other",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Unit Price",
            "expression": "ROUND(sum(FactSales[UnitPrice]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Qty",
            "expression": "sum(FactSales[SalesQty])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Other",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Percent",
            "expression": "SUM(FactSales[DiscountPercent])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "expression": "SUM(FactSales[DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Amount",
            "expression": "MAX([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Minimum of Discount Amount",
            "expression": "MIN([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Percent",
            "expression": "MAX([DiscountPercent])",
            "displayFolder": "Discount"
          },
          {
            "name": "Minimum of DiscountPercent",
            "expression": "MIN([DiscountPercent])",
            "displayFolder": "Discount"
          },
          {
            "name": "Count Of Product",
            "expression": "DISTINCTCOUNT (FactSales[ProductKey])",
            "displayFolder": "Other"
          },
          {
            "name": "Average per Day",
            "expression": " DIVIDE(sum(FactSales[AmountAfterTax]),DISTINCTCOUNT(FactSales[Order Date])) ",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Average",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Average per Order",
            "expression": " DIVIDE(sum(FactSales[AmountAfterTax]),DISTINCTCOUNT(FactSales[Sales Order])) ",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Average",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Day",
            "expression": "DISTINCTCOUNT(FactSales[Order Date])",
            "formatString": "0"
          }
        ]
      },
      {
        "name": "DimCar",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "sourceColumn": "CarKey"
          },
          {
            "name": "CarAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CarAlternativeKey"
          },
          {
            "name": "Car Number",
            "dataType": "string",
            "sourceColumn": "CarNumber"
          },
          {
            "name": "Car Name",
            "dataType": "string",
            "sourceColumn": "CarName"
          },
          {
            "name": "Car Type",
            "dataType": "int64",
            "sourceColumn": "CarType"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCar = Source{[Schema=\"dbo\",Item=\"DimCar\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimCar, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimCompany",
        "columns": [
          {
            "name": "Companykey",
            "dataType": "int64",
            "sourceColumn": "Companykey"
          },
          {
            "name": "CompanyAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CompanyAlternativeKey"
          },
          {
            "name": "CompanyName",
            "dataType": "string",
            "sourceColumn": "CompanyName"
          },
          {
            "name": "Desc",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Desc"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCompany = Source{[Schema=\"dbo\",Item=\"DimCompany\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimCompany, each ([Companykey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "Customer No.",
            "dataType": "string",
            "sourceColumn": "CustomerAlternativeKey"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Customer Group",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "CustomerType"
          },
          {
            "name": "Classification",
            "dataType": "string",
            "sourceColumn": "CustomerClassification"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          },
          {
            "name": "CustomerNameFull",
            "dataType": "string",
            "sourceColumn": "CustomerNameFull"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimCustomer, each ([CompanyKey] = 3)),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows\",{{\"CustomerName\", \"CustomerNameFull\"}}),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Renamed Columns\", \"CustomerName\", each Text.BeforeDelimiter([CustomerNameFull], \" \", 1), type text),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Inserted Text Before Delimiter\",{\"CompanyKey\", \"CustomerKey\", \"CustomerAlternativeKey\", \"CustomerNameFull\", \"CustomerName\", \"CustomerGroup\", \"CustomerType\", \"CustomerClassification\", \"Birthday\", \"Gender\", \"UpdatLasteTime\", \"FactSales\"})",
                "in",
                "    #\"Reordered Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimDimension",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "DimensionAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DimensionAlternativeKey"
          },
          {
            "name": "LocationId",
            "dataType": "string",
            "sourceColumn": "InventLocationId"
          },
          {
            "name": "Warehouse",
            "dataType": "string",
            "sourceColumn": "WarehouseName"
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "SiteName"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "ColorName"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "SizeName"
          },
          {
            "name": "Configration",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ConfigrationName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDimension = Source{[Schema=\"dbo\",Item=\"DimDimension\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimDimension, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "EmployeeID",
            "dataType": "string",
            "sourceColumn": "EmployeeAlternativeKey"
          },
          {
            "name": "Employee",
            "dataType": "string",
            "sourceColumn": "EmployeeName"
          },
          {
            "name": "Job",
            "dataType": "string",
            "sourceColumn": "Job"
          },
          {
            "name": "Departmen",
            "dataType": "string",
            "sourceColumn": "DepartmenName"
          },
          {
            "name": "Division",
            "dataType": "string",
            "sourceColumn": "DivisionName"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "Contract Type",
            "dataType": "string",
            "sourceColumn": "ContractType"
          },
          {
            "name": "ContractDate",
            "dataType": "dateTime",
            "sourceColumn": "ContractDate"
          },
          {
            "name": "Contract End Date",
            "dataType": "dateTime",
            "sourceColumn": "ContractEndDate"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "Hire Date",
            "dataType": "dateTime",
            "sourceColumn": "HireDate"
          },
          {
            "name": "InsuranceDate",
            "dataType": "dateTime",
            "sourceColumn": "InsuranceDate"
          },
          {
            "name": "Worke Status",
            "dataType": "string",
            "sourceColumn": "WorkeStatus"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          },
          {
            "name": "EmployeeNameFull",
            "dataType": "string",
            "sourceColumn": "EmployeeNameFull"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimEmployee, each ([CompanyKey] = 3)),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Filtered Rows\",{{\"EmployeeName\", Text.Clean, type text}}),",
                "    #\"Inserted Text Before Delimiter\" = Table.AddColumn(#\"Cleaned Text\", \"Text Before Delimiter\", each Text.BeforeDelimiter([EmployeeName], \" \", 1), type text),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Inserted Text Before Delimiter\",{\"CompanyKey\", \"EmployeeKey\", \"EmployeeAlternativeKey\", \"EmployeeName\", \"Text Before Delimiter\", \"Job\", \"DepartmenName\", \"DivisionName\", \"Gender\", \"ContractType\", \"ContractDate\", \"ContractEndDate\", \"BirthDate\", \"HireDate\", \"InsuranceDate\", \"WorkeStatus\", \"UpdatLasteTime\", \"FactPurchase\", \"FactSalary\", \"FactSales\", \"FactSalesCommission\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"EmployeeName\", \"EmployeeNameFull\"}, {\"Text Before Delimiter\", \"EmployeeName\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimOrderStatus",
        "columns": [
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusKey"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "StatusName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixOrderStatus = Source{[Schema=\"dbo\",Item=\"DimFixOrderStatus\"]}[Data]",
                "in",
                "    dbo_DimFixOrderStatus"
              ]
            }
          }
        ]
      },
      {
        "name": "DimSalesType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "Type Name",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixSalesType = Source{[Schema=\"dbo\",Item=\"DimFixSalesType\"]}[Data]",
                "in",
                "    dbo_DimFixSalesType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "GeographyAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyAlternativeKey"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "RegionName"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "StateName"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "CityName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimGeography, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyGeography",
            "levels": [
              {
                "name": "Region",
                "ordinal": 0,
                "column": "Region"
              },
              {
                "name": "State",
                "ordinal": 1,
                "column": "State"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City"
              }
            ]
          }
        ]
      },
      {
        "name": "DimMethodAcquisition",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodAcquisitionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionAlternativeKey"
          },
          {
            "name": "Acquisition",
            "dataType": "string",
            "sourceColumn": "NameMethodAcquisition"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodAcquisition = Source{[Schema=\"dbo\",Item=\"DimMethodAcquisition\"]}[Data]",
                "in",
                "    dbo_DimMethodAcquisition"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodDelivery",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodDeliveryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliveryKey"
          },
          {
            "name": "MethodDeliveryAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliveryAlternativeKey"
          },
          {
            "name": "Delivery",
            "dataType": "string",
            "sourceColumn": "NameMethodDelivery"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodDelivery = Source{[Schema=\"dbo\",Item=\"DimMethodDelivery\"]}[Data]",
                "in",
                "    dbo_DimMethodDelivery"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodPayment",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodPaymentKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodPaymentKey"
          },
          {
            "name": "MethodPaymentAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodPaymentAlternativeKey"
          },
          {
            "name": "Payment",
            "dataType": "string",
            "sourceColumn": "NameMethodsPayment"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodPayment = Source{[Schema=\"dbo\",Item=\"DimMethodPayment\"]}[Data]",
                "in",
                "    dbo_DimMethodPayment"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternativeKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternativeKey"
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "SubCategory",
            "dataType": "string",
            "sourceColumn": "SubCategory"
          },
          {
            "name": "StatusCategory",
            "dataType": "string",
            "sourceColumn": "StatusCategory"
          },
          {
            "name": "StatusProduct",
            "dataType": "string",
            "sourceColumn": "StatusProduct"
          },
          {
            "name": "GroupType",
            "dataType": "string",
            "sourceColumn": "GroupType"
          },
          {
            "name": "SalesPrice",
            "dataType": "decimal",
            "sourceColumn": "SalesPrice"
          },
          {
            "name": "PurchasePrice",
            "dataType": "decimal",
            "sourceColumn": "PurchasePrice"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "boolean",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimProduct, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales Price",
            "expression": "sum(DimProduct[SalesPrice])"
          },
          {
            "name": "AVG Price",
            "expression": "AVERAGE(DimProduct[SalesPrice])"
          },
          {
            "name": "Count Product",
            "expression": "COUNT(DimProduct[ProductAlternativeKey])"
          }
        ]
      },
      {
        "name": "DimPromotion",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "PromotionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionAlternativeKey"
          },
          {
            "name": "STATUS",
            "dataType": "int64",
            "sourceColumn": "STATUS"
          },
          {
            "name": "FROMDATE",
            "dataType": "dateTime",
            "sourceColumn": "FROMDATE"
          },
          {
            "name": "TODATE",
            "dataType": "dateTime",
            "sourceColumn": "TODATE"
          },
          {
            "name": "DELIVERYDATE",
            "dataType": "dateTime",
            "sourceColumn": "DELIVERYDATE"
          },
          {
            "name": "DESCRIPTION",
            "dataType": "string",
            "sourceColumn": "DESCRIPTION"
          },
          {
            "name": "ITEMGROUP",
            "dataType": "string",
            "sourceColumn": "ITEMGROUP"
          },
          {
            "name": "DESCACTIVE",
            "dataType": "int64",
            "sourceColumn": "DESCACTIVE"
          },
          {
            "name": "SORTDISC",
            "dataType": "int64",
            "sourceColumn": "SORTDISC"
          },
          {
            "name": "PRICEDISCOUNT",
            "dataType": "decimal",
            "sourceColumn": "PRICEDISCOUNT"
          },
          {
            "name": "DISCOUNT",
            "dataType": "double",
            "sourceColumn": "DISCOUNT"
          },
          {
            "name": "QUANTITY",
            "dataType": "int64",
            "sourceColumn": "QUANTITY"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimPromotion = Source{[Schema=\"dbo\",Item=\"DimPromotion\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimPromotion, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimUnit",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "sourceColumn": "UnitKey"
          },
          {
            "name": "UnitAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "UnitAlternativeKey"
          },
          {
            "name": "UnitName",
            "dataType": "string",
            "sourceColumn": "UnitName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimUnit = Source{[Schema=\"dbo\",Item=\"DimUnit\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimUnit, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimBranche",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "Branche Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey",
            "formatString": "0",
            "sortByColumn": "Branche Sort"
          },
          {
            "name": "BrancheAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BrancheAlternativeKey"
          },
          {
            "name": "BrancheName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BrancheName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime",
            "formatString": "General Date"
          },
          {
            "name": "Branche Sort",
            "dataType": "int64",
            "sourceColumn": "BrancheSort",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Branche",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " if([CompanyKey]==3,[BrancheName],[BrancheName] & \" \" & [CompanyKey])",
            "sortByColumn": "Branche Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimBranche = Source{[Schema=\"dbo\",Item=\"DimBranche\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimBranche, each ([CompanyKey] = 3) and ([BrancheName] <> \"None\" and [BrancheName] <> \"الدور الخامس\" and [BrancheName] <> \"مخزن نصف جاهز\" and [BrancheName] <> \"نشارة\"))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "dd-MM-yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"dd-MM-yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "FullDate",
            "dataType": "string",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "int64",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "int64",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "int64",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "Season",
            "dataType": "string",
            "sourceColumn": "Season"
          },
          {
            "name": "Semester",
            "dataType": "string",
            "sourceColumn": "Semester"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimDate, each Date.IsInPreviousNYears([Date], 10) or Date.IsInCurrentYear([Date]))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyDate",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "DayOfMonth"
              }
            ]
          }
        ]
      },
      {
        "name": "FactSalesOrder",
        "columns": [
          {
            "name": "Sales Order",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CarKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodDeliverykey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliverykey"
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey"
          },
          {
            "name": "OrderDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateAlternativeKey"
          },
          {
            "name": "ProductionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductionDateAlternativeKey"
          },
          {
            "name": "ShippingDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippingDateAlternativeKey"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "displayFolder": "Date"
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "sourceColumn": "ProductionDate",
            "displayFolder": "Date"
          },
          {
            "name": "Shipping Date",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate",
            "displayFolder": "Date"
          },
          {
            "name": "Discount%",
            "dataType": "double",
            "sourceColumn": "DiscountPercent",
            "displayFolder": "Amount",
            "summarizeBy": "none"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountAmount",
            "displayFolder": "Amount"
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LineAmount"
          },
          {
            "name": "AmountAfterTax",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountAfterTax",
            "displayFolder": "Amount"
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmount"
          },
          {
            "name": "Payment",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Payment",
            "displayFolder": "Amount"
          },
          {
            "name": "Create Date Time",
            "dataType": "dateTime",
            "sourceColumn": "CreateDateTime",
            "displayFolder": "Date"
          },
          {
            "type": "calculated",
            "name": "Payment %",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "ROUNDUP(IFERROR(DIVIDE(FactSalesOrder[Payment],FactSalesOrder[AmountAfterTax]),0),2)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Amount"
          },
          {
            "name": "StatusOrderKey",
            "dataType": "int64",
            "sourceColumn": "StatusOrderKey"
          },
          {
            "name": "TypeKey",
            "dataType": "int64",
            "sourceColumn": "TypeKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSalesOrder = Source{[Schema=\"dbo\",Item=\"FactSalesOrder\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactSalesOrder, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "#Count SO Order",
            "expression": "DISTINCTCOUNT(FactSalesOrder[Sales Order])",
            "displayFolder": "Amount"
          },
          {
            "name": "#Discount Amount",
            "expression": "SUM(FactSalesOrder[DiscountAmount])",
            "displayFolder": "Amount"
          },
          {
            "name": "#Total Amount",
            "expression": "round(sum(FactSalesOrder[AmountAfterTax]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "#Total Payment",
            "expression": "round(sum(FactSalesOrder[Payment]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "kpi": {
              "targetExpression": "'FactSalesOrder'[#Total Amount]",
              "targetFormatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
              "statusGraphic": "Road Signs",
              "statusExpression": [
                "var x='FactSalesOrder'[#Total Payment]/'FactSalesOrder'[_#Total Payment Goal] return",
                "            if(ISBLANK(x),BLANK(),",
                "                    If(x<0.499,-1,",
                "\t                If(x<0.999,0,1)",
                "                )",
                "            )",
                "            "
              ],
              "annotations": [
                {
                  "name": "GoalType",
                  "value": "Measure"
                },
                {
                  "name": "KpiStatusType",
                  "value": "Linear"
                },
                {
                  "name": "KpiThresholdType",
                  "value": "Percentage"
                },
                {
                  "name": "KpiThresholdOrdering",
                  "value": "Ascending"
                },
                {
                  "name": "KpiThresholdCount",
                  "value": "2"
                },
                {
                  "name": "KpiThreshold_0",
                  "value": "49.9"
                },
                {
                  "name": "KpiThreshold_1",
                  "value": "99.9"
                }
              ]
            },
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "FactSalesCommission",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "SalesCommissionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionKey"
          },
          {
            "name": "SalesCommissionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionAlternativeKey"
          },
          {
            "name": "TargetLevelkey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TargetLevelkey"
          },
          {
            "name": "EmpTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmpTypeKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "SalesCommissionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionDateAlternativeKey"
          },
          {
            "name": "SalesCommissionDateKey",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "SalesCommissionDateKey"
          },
          {
            "name": "Precent",
            "dataType": "double",
            "sourceColumn": "Precent"
          },
          {
            "name": "AmountFrom",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountFrom"
          },
          {
            "name": "AmountTo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountTo"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Amount"
          },
          {
            "name": "TotalSales",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TotalSales"
          },
          {
            "name": "CountSo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CountSo"
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          },
          {
            "name": "DgreeName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DimTargetLevel.DgreeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSalesCommission = Source{[Schema=\"dbo\",Item=\"FactSalesCommission\"]}[Data],",
                "    #\"Expanded DimTargetLevel\" = Table.ExpandRecordColumn(dbo_FactSalesCommission, \"DimTargetLevel\", {\"DgreeName\"}, {\"DimTargetLevel.DgreeName\"})",
                "in",
                "    #\"Expanded DimTargetLevel\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Commission Amount",
            "expression": "sum(FactSalesCommission[Amount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Sales",
            "expression": "sum(FactSalesCommission[TotalSales])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of SO Commission",
            "expression": "SUM(FactSalesCommission[CountSo])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Employee",
            "expression": "DISTINCTCOUNT(FactSalesCommission[EmployeeKey])"
          },
          {
            "name": "Average per Employee",
            "expression": "DIVIDE(FactSalesCommission[Commission Amount],FactSalesCommission[Count Of Employee])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Average per Month",
            "expression": "DIVIDE(FactSalesCommission[Commission Amount],FactSalesCommission[Count Of Month])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Month",
            "expression": "DISTINCTCOUNT(FactSalesCommission[SalesCommissionDateAlternativeKey])"
          },
          {
            "name": "Maximum of DgreeName",
            "expression": "MAX([DgreeName])"
          },
          {
            "name": "Maximum of TargetLevelkey",
            "expression": "sum([TargetLevelkey])"
          }
        ]
      },
      {
        "name": "DimEmpType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "TypeName",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmpType = Source{[Schema=\"dbo\",Item=\"DimEmpType\"]}[Data]",
                "in",
                "    dbo_DimEmpType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimFinTransType",
        "columns": [
          {
            "name": "TransTypeKey",
            "dataType": "int64",
            "sourceColumn": "TransTypeKey"
          },
          {
            "name": "TransTypeName",
            "dataType": "string",
            "sourceColumn": "TransTypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixFinTransType = Source{[Schema=\"dbo\",Item=\"DimFixFinTransType\"]}[Data]",
                "in",
                "    dbo_DimFixFinTransType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactFinance",
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Id"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "AccountKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountKey"
          },
          {
            "name": "FinancialDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FinancialDateAlternativeKey"
          },
          {
            "name": "TransTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TransTypeKey"
          },
          {
            "name": "FinancialDate",
            "dataType": "dateTime",
            "sourceColumn": "FinancialDate"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Amount"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          },
          {
            "name": "PostingType",
            "dataType": "int64",
            "sourceColumn": "PostingType"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactFinance = Source{[Schema=\"dbo\",Item=\"FactFinance\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_FactFinance, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Finance Amount",
            "expression": "sum(FactFinance[Amount])"
          }
        ]
      },
      {
        "name": "DimAccount",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "AccountKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountKey"
          },
          {
            "name": "AccountAlternativeKey",
            "dataType": "string",
            "sourceColumn": "AccountAlternativeKey"
          },
          {
            "name": "AccountName",
            "dataType": "string",
            "sourceColumn": "AccountName"
          },
          {
            "name": "AccountType",
            "dataType": "int64",
            "sourceColumn": "AccountType"
          },
          {
            "name": "AccountGroup",
            "dataType": "int64",
            "sourceColumn": "AccountGroup"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimAccount = Source{[Schema=\"dbo\",Item=\"DimAccount\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimAccount, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimAccountCategory",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "AccountCategoryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountCategoryKey"
          },
          {
            "name": "AccountCategoryAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AccountCategoryAlternativeKey"
          },
          {
            "name": "AccountCategoryName",
            "dataType": "string",
            "sourceColumn": "AccountCategoryName",
            "sortByColumn": "SortGroup"
          },
          {
            "name": "DescriptionGroup",
            "dataType": "string",
            "sourceColumn": "DescriptionGroup"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          },
          {
            "name": "SortGroup",
            "dataType": "int64",
            "sourceColumn": "SortGroup"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimAccountCategory = Source{[Schema=\"dbo\",Item=\"DimAccountCategory\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimAccountCategory, each true)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DateTime",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date]",
            "formatString": "dd-MM-yyyy h:mm:ss AM/PM",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"dd-MM-yyyy h:mm:ss tt\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Time",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "Now()",
            "formatString": "dd-MM-yyyy h:mm:ss AM/PM",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"dd-MM-yyyy h:mm:ss tt\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALENDAR(UTCNOW(),UTCNOW())"
            }
          }
        ]
      },
      {
        "name": "DimFixFinPostingType",
        "columns": [
          {
            "name": "PostingTypeKey",
            "dataType": "int64",
            "sourceColumn": "PostingTypeKey"
          },
          {
            "name": "PostingTypeName",
            "dataType": "string",
            "sourceColumn": "PostingTypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixFinPostingType = Source{[Schema=\"dbo\",Item=\"DimFixFinPostingType\"]}[Data]",
                "in",
                "    dbo_DimFixFinPostingType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimFixFinOffsetAccountType",
        "columns": [
          {
            "name": "OffsetAccountTypeKey",
            "dataType": "int64",
            "sourceColumn": "OffsetAccountTypeKey"
          },
          {
            "name": "OffsetAccountTypeName",
            "dataType": "string",
            "sourceColumn": "OffsetAccountTypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixFinOffsetAccountType = Source{[Schema=\"dbo\",Item=\"DimFixFinOffsetAccountType\"]}[Data]",
                "in",
                "    dbo_DimFixFinOffsetAccountType"
              ]
            }
          }
        ]
      },
      {
        "name": "FactBank",
        "isHidden": true,
        "columns": [
          {
            "name": "Id",
            "dataType": "int64",
            "sourceColumn": "Id"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "AccountKey",
            "dataType": "int64",
            "sourceColumn": "AccountKey"
          },
          {
            "name": "OffsetAccountKey",
            "dataType": "int64",
            "sourceColumn": "OffsetAccountKey"
          },
          {
            "name": "PaymentDateAlternativeKey",
            "dataType": "int64",
            "sourceColumn": "PaymentDateAlternativeKey"
          },
          {
            "name": "AccountType",
            "dataType": "int64",
            "sourceColumn": "AccountType"
          },
          {
            "name": "OffsetAccountType",
            "dataType": "int64",
            "sourceColumn": "OffsetAccountType"
          },
          {
            "name": "PaymentDate",
            "dataType": "dateTime",
            "sourceColumn": "PaymentDate"
          },
          {
            "name": "JournalNum",
            "dataType": "string",
            "sourceColumn": "JournalNum"
          },
          {
            "name": "AmountDebit",
            "dataType": "double",
            "sourceColumn": "AmountDebit"
          },
          {
            "name": "AmountCredit",
            "dataType": "double",
            "sourceColumn": "AmountCredit"
          },
          {
            "name": "SalesId",
            "dataType": "string",
            "sourceColumn": "SalesId"
          },
          {
            "name": "Voucher",
            "dataType": "string",
            "sourceColumn": "Voucher"
          },
          {
            "name": "txt",
            "dataType": "string",
            "sourceColumn": "txt"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "sourceColumn": "LastupdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactBank = Source{[Schema=\"dbo\",Item=\"FactBank\"]}[Data]",
                "in",
                "    dbo_FactBank"
              ]
            }
          }
        ]
      },
      {
        "name": "FactPymentCustomer",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Id",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[Id]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "CompanyKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "FactBank[CompanyKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "AccountKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "FactBank[AccountKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OffsetAccountKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "FactBank[OffsetAccountKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "PaymentDateAlternativeKey",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "FactBank[PaymentDateAlternativeKey]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "AccountType",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "FactBank[AccountType]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OffsetAccountType",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "FactBank[OffsetAccountType]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "PaymentDate",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[PaymentDate]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "JournalNum",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[JournalNum]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "AmountDebit",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[AmountDebit]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "AmountCredit",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[AmountCredit]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SalesId",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[SalesId]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Voucher",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[Voucher]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "txt",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "FactBank[txt]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "FactBank[LastupdateDate]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALCULATETABLE(FactBank,FactBank[AccountType]=1 &&  FactBank[OffsetAccountType]=6 && FactBank[CompanyKey]=3)"
            }
          }
        ],
        "measures": [
          {
            "name": "Payment Amount",
            "expression": " sum(FactPymentCustomer[AmountCredit])",
            "formatString": "\"\"#,0.00;(\"\"#,0.00);\"\"#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "#CountID",
            "expression": "COUNT(FactPymentCustomer[Id])"
          }
        ]
      },
      {
        "name": "DimBank",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "BankKey",
            "dataType": "int64",
            "sourceColumn": "BankKey"
          },
          {
            "name": "BankAlternativeKey",
            "dataType": "string",
            "sourceColumn": "BankAlternativeKey"
          },
          {
            "name": "BnakName",
            "dataType": "string",
            "sourceColumn": "BnakName"
          },
          {
            "name": "BankGroupName",
            "dataType": "string",
            "sourceColumn": "BankGroupName"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "AccountKey",
            "dataType": "int64",
            "sourceColumn": "AccountKey"
          },
          {
            "name": "CurrencyCode",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimBank = Source{[Schema=\"dbo\",Item=\"DimBank\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimBank, each ([CompanyKey] = 3))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "DimTargetLevel",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "TargetLevelKey",
            "dataType": "int64",
            "sourceColumn": "TargetLevelKey"
          },
          {
            "name": "DgreeName",
            "dataType": "string",
            "sourceColumn": "DgreeName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimTargetLevel = Source{[Schema=\"dbo\",Item=\"DimTargetLevel\"]}[Data]",
                "in",
                "    dbo_DimTargetLevel"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "efcc7883-a565-4dfd-9a51-1b3ee580e8a7",
        "fromTable": "FactSales",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "20a4f5a8-dc1b-425c-b945-32227fcfc412",
        "fromTable": "FactSales",
        "fromColumn": "StatusKey",
        "toTable": "DimOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "6f52df78-743c-42be-9b14-6b7827a890b0",
        "fromTable": "FactSales",
        "fromColumn": "TypeKey",
        "toTable": "DimSalesType",
        "toColumn": "TypeKey"
      },
      {
        "name": "a8a9a89f-90b1-4ebc-9808-8437e634cfe2",
        "fromTable": "FactSales",
        "fromColumn": "CarKey",
        "toTable": "DimCar",
        "toColumn": "CarKey"
      },
      {
        "name": "671e7041-af90-4534-9e1d-bf70eee94922",
        "fromTable": "FactSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "75b87e4a-c9f4-4381-a2a8-f1fa8687c0fe",
        "fromTable": "FactSales",
        "fromColumn": "DimensionKey",
        "toTable": "DimDimension",
        "toColumn": "DimensionKey"
      },
      {
        "name": "081c882e-a615-4c92-97e5-0d90b34e3524",
        "fromTable": "FactSales",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "7bfbef40-1be6-47d8-b553-00605b9e71fe",
        "fromTable": "FactSales",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "5abc277d-ce70-4f78-996a-190d3de74032",
        "fromTable": "FactSales",
        "fromColumn": "MethodAcquisitionKey",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "d223a52a-cb58-44b7-ae13-70135d56570b",
        "fromTable": "FactSales",
        "fromColumn": "MethodDeliverykey",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "934f097e-9a0a-4860-838e-901584f6065f",
        "fromTable": "FactSales",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "9c161b3d-7507-4639-a51f-72b0560714aa",
        "fromTable": "FactSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "6d62c46f-4e0d-48d7-a479-b881f40f845c",
        "fromTable": "FactSales",
        "fromColumn": "PromotionKey",
        "toTable": "DimPromotion",
        "toColumn": "PromotionKey"
      },
      {
        "name": "a6c99fd9-5295-4781-9f3c-11d58f62b6cc",
        "fromTable": "FactSales",
        "fromColumn": "UnitKey",
        "toTable": "DimUnit",
        "toColumn": "UnitKey"
      },
      {
        "name": "88ffaa6a-2caf-46f6-b43e-8544725699d2",
        "fromTable": "FactSales",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "c4fd38a7-8477-4bac-8505-702a11a9ba54",
        "fromTable": "FactSales",
        "fromColumn": "ProductionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "a34a0957-168b-4eef-9dac-64692bcac096",
        "fromTable": "FactSales",
        "fromColumn": "ShippingDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "b862e642-d68d-4d26-83ad-2f444abcf77b",
        "fromTable": "FactSales",
        "fromColumn": "OrderDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "06188c81-c4cf-422d-b7b5-5621222e0ff6",
        "fromTable": "FactSalesOrder",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "f181d3ab-c2c1-443f-8a5d-5aa2a677423d",
        "fromTable": "FactSalesOrder",
        "fromColumn": "CarKey",
        "toTable": "DimCar",
        "toColumn": "CarKey"
      },
      {
        "name": "7660bf2d-a30f-4bcf-bae0-c038881dd2a8",
        "fromTable": "FactSalesOrder",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "32e2d270-253b-4e04-8a9a-b76e7c3b5af0",
        "fromTable": "FactSalesOrder",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "2d614aad-bb7d-448a-9338-f36da580b64c",
        "fromTable": "FactSalesOrder",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "106d8afe-f5c2-4278-9789-bea2ed54e9c7",
        "fromTable": "FactSalesOrder",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "288f0e24-e57e-4279-add4-21dac18d5bca",
        "fromTable": "FactSalesOrder",
        "fromColumn": "ShippingDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "19022772-562f-4f91-8f70-6bce7e65f9f2",
        "fromTable": "FactSalesOrder",
        "fromColumn": "MethodAcquisitionKey",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "8d021442-d847-4f7f-b2d5-6ec66cce5878",
        "fromTable": "FactSalesOrder",
        "fromColumn": "MethodDeliverykey",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "af7e2fde-07f7-450c-8546-2d7ff79e5c45",
        "fromTable": "FactSalesOrder",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "6261b00d-44aa-4c39-8a0b-ff1a4d9a8953",
        "fromTable": "FactSalesOrder",
        "fromColumn": "ProductionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "925a6813-f6c7-4db5-8d09-d0f246819518",
        "fromTable": "FactSalesOrder",
        "fromColumn": "OrderDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "c91cece1-7ba9-4289-bf40-fbcbc253d499",
        "fromTable": "FactSalesOrder",
        "fromColumn": "StatusOrderKey",
        "toTable": "DimOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "a7a51300-dc16-4fa7-96d6-ee1b8d060343",
        "fromTable": "FactSalesCommission",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "fec133e3-e7be-4e46-94b9-f992582d577d",
        "fromTable": "FactSalesCommission",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "1ee28abb-ea43-4b08-8f26-7f3def0ff1bd",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "4cdf3c14-110c-49b2-bcd0-3509dd9c937e",
        "fromTable": "FactSalesCommission",
        "fromColumn": "SalesCommissionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "72095038-4166-48fe-9088-9d9dbd41b74d",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmpTypeKey",
        "toTable": "DimEmpType",
        "toColumn": "TypeKey"
      },
      {
        "name": "81a3f43c-4015-4618-8c51-40ebe082052c",
        "fromTable": "FactFinance",
        "fromColumn": "AccountKey",
        "toTable": "DimAccount",
        "toColumn": "AccountKey"
      },
      {
        "name": "870c3d0d-085c-479b-b916-10d73f2a9ef8",
        "fromTable": "FactFinance",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "5405fd2c-05df-4c58-9a9d-5fe6201b936a",
        "fromTable": "FactFinance",
        "fromColumn": "FinancialDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "ce0bd279-0635-4e88-a31f-22eb99cb23ec",
        "fromTable": "FactFinance",
        "fromColumn": "TransTypeKey",
        "toTable": "DimFinTransType",
        "toColumn": "TransTypeKey"
      },
      {
        "name": "80d0cb0b-c3b2-4b79-87a3-bb41615e8173",
        "fromTable": "DimAccount",
        "fromColumn": "AccountGroup",
        "toTable": "DimAccountCategory",
        "toColumn": "AccountCategoryKey"
      },
      {
        "name": "19f7e126-2764-4ccb-9aea-1584fcd9c462",
        "fromTable": "FactFinance",
        "fromColumn": "PostingType",
        "toTable": "DimFixFinPostingType",
        "toColumn": "PostingTypeKey"
      },
      {
        "name": "5b9fb114-7a49-4d43-8797-24ec8db86199",
        "fromTable": "FactBank",
        "fromColumn": "PaymentDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "00433f79-90ef-4e9d-bb3d-d3aa366116f8",
        "fromTable": "FactBank",
        "fromColumn": "OffsetAccountType",
        "toTable": "DimFixFinOffsetAccountType",
        "toColumn": "OffsetAccountTypeKey"
      },
      {
        "name": "3b39cb40-da38-415d-835b-b88464be3e54",
        "fromTable": "FactBank",
        "fromColumn": "AccountType",
        "toTable": "DimFixFinOffsetAccountType",
        "toColumn": "OffsetAccountTypeKey",
        "isActive": false
      },
      {
        "name": "f2ab16de-67a3-46c6-af95-b980dcc787bc",
        "fromTable": "FactBank",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "63c11b39-3cfa-469b-af84-8fbb8760d899",
        "fromTable": "FactPymentCustomer",
        "fromColumn": "AccountKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "f4f44107-4c7a-420a-adf1-7b3c02394a1e",
        "fromTable": "FactPymentCustomer",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "eca6b78a-35c9-4c5b-9eda-7e918f25d474",
        "fromTable": "FactPymentCustomer",
        "fromColumn": "OffsetAccountKey",
        "toTable": "DimBank",
        "toColumn": "BankKey"
      },
      {
        "name": "e57bbd47-9e83-4ffe-a68d-880e3ef08bab",
        "fromTable": "FactPymentCustomer",
        "fromColumn": "AccountType",
        "toTable": "DimFixFinOffsetAccountType",
        "toColumn": "OffsetAccountTypeKey"
      },
      {
        "name": "55c99e27-0730-4810-91ef-f9d84e73aadb",
        "fromTable": "FactPymentCustomer",
        "fromColumn": "OffsetAccountKey",
        "toTable": "DimFixFinOffsetAccountType",
        "toColumn": "OffsetAccountTypeKey",
        "isActive": false
      },
      {
        "name": "51c80d5f-7245-42dd-a2f4-81ee35b7c48c",
        "fromTable": "DimBank",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "ec71a141-7ec9-4613-9fde-13c5cd7fb143",
        "fromTable": "FactPymentCustomer",
        "fromColumn": "PaymentDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "31314b21-1e75-4df0-ada6-262091529533",
        "fromTable": "FactSalesCommission",
        "fromColumn": "TargetLevelkey",
        "toTable": "DimTargetLevel",
        "toColumn": "TargetLevelKey"
      }
    ],
    "cultures": [
      {
        "name": "ar-EG"
      }
    ],
    "roles": [
      {
        "name": "User",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "DimCompany",
            "filterExpression": "[Companykey]=3"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}