{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/hyperv-srv;DataWarehouse",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "mffco-srv",
            "database": "DataWarehouse"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "FactSales",
        "columns": [
          {
            "name": "Invent Trance Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "InventTranceKey"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "UnitKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusKey"
          },
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CarKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodDeliverykey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliverykey"
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey"
          },
          {
            "name": "OrderDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateAlternativeKey"
          },
          {
            "name": "ProductionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductionDateAlternativeKey"
          },
          {
            "name": "ShippingDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippingDateAlternativeKey"
          },
          {
            "name": "Sales Order",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "SalesOrderLineNumber",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesOrderLineNumber"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "formatString": "Short Date",
            "displayFolder": "Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "sourceColumn": "ProductionDate",
            "formatString": "dd-MM-yyyy",
            "displayFolder": "Date"
          },
          {
            "name": "Shipping Date",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate",
            "formatString": "Short Date",
            "displayFolder": "Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "UnitPrice",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "SalesQty",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesQty"
          },
          {
            "name": "DiscountPercent",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountPercent"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LineAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "AmountAfterTax",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountAfterTax",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmount",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Payment",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Payment",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          },
          {
            "name": "Create Date Time",
            "dataType": "dateTime",
            "sourceColumn": "CreateDateTime",
            "displayFolder": "Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data]",
                "in",
                "    dbo_FactSales"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Line Amount",
            "expression": "ROUND(sum(FactSales[LineAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Amount",
            "description": "Total Amount After Tax",
            "expression": "round(sum(FactSales[AmountAfterTax]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Tax Amount",
            "expression": "round(sum(FactSales[TaxAmount]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Total Payment",
            "expression": "round(sum(FactSales[Payment]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of SO",
            "expression": "DISTINCTCOUNT(FactSales[Sales Order])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Other",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Unit Price",
            "expression": "ROUND(sum(FactSales[UnitPrice]),0)",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Amount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Count Of Qty",
            "expression": "sum(FactSales[SalesQty])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Other",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Percent",
            "expression": "SUM(FactSales[DiscountPercent])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "expression": "SUM(FactSales[DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Amount",
            "expression": "MAX([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Minimum of Discount Amount",
            "expression": "MIN([DiscountAmount])",
            "formatString": "\"\"#,0;(\"\"#,0);\"\"#,0",
            "displayFolder": "Discount",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Maximum of Discount Percent",
            "expression": "MAX([DiscountPercent])",
            "displayFolder": "Discount"
          },
          {
            "name": "Minimum of DiscountPercent",
            "expression": "MIN([DiscountPercent])",
            "displayFolder": "Discount"
          },
          {
            "name": "Count Of Product",
            "expression": "DISTINCTCOUNT (FactSales[ProductKey])",
            "displayFolder": "Other"
          },
          {
            "name": "Average per Day",
            "expression": " DIVIDE(sum(FactSales[AmountAfterTax]),DISTINCTCOUNT(FactSales[Order Date])) ",
            "formatString": "0",
            "displayFolder": "Average"
          },
          {
            "name": "Average per Order",
            "expression": " DIVIDE(sum(FactSales[AmountAfterTax]),DISTINCTCOUNT(FactSales[Sales Order])) ",
            "formatString": "0",
            "displayFolder": "Average"
          },
          {
            "name": "Count Of Day",
            "expression": "DISTINCTCOUNT(FactSales[Order Date])",
            "formatString": "0"
          }
        ]
      },
      {
        "name": "DimCar",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "sourceColumn": "CarKey"
          },
          {
            "name": "CarAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CarAlternativeKey"
          },
          {
            "name": "Car Number",
            "dataType": "string",
            "sourceColumn": "CarNumber"
          },
          {
            "name": "Car Name",
            "dataType": "string",
            "sourceColumn": "CarName"
          },
          {
            "name": "Car Type",
            "dataType": "int64",
            "sourceColumn": "CarType"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "Description"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCar = Source{[Schema=\"dbo\",Item=\"DimCar\"]}[Data]",
                "in",
                "    dbo_DimCar"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCompany",
        "columns": [
          {
            "name": "Companykey",
            "dataType": "int64",
            "sourceColumn": "Companykey"
          },
          {
            "name": "CompanyAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CompanyAlternativeKey"
          },
          {
            "name": "CompanyName",
            "dataType": "string",
            "sourceColumn": "CompanyName"
          },
          {
            "name": "Desc",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Desc"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCompany = Source{[Schema=\"dbo\",Item=\"DimCompany\"]}[Data]",
                "in",
                "    dbo_DimCompany"
              ]
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "Customer No.",
            "dataType": "string",
            "sourceColumn": "CustomerAlternativeKey"
          },
          {
            "name": "Customer",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Customer Group",
            "dataType": "string",
            "sourceColumn": "CustomerGroup"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "CustomerType"
          },
          {
            "name": "Classification",
            "dataType": "string",
            "sourceColumn": "CustomerClassification"
          },
          {
            "name": "Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Birthday"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDimension",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "DimensionKey",
            "dataType": "int64",
            "sourceColumn": "DimensionKey"
          },
          {
            "name": "DimensionAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DimensionAlternativeKey"
          },
          {
            "name": "LocationId",
            "dataType": "string",
            "sourceColumn": "InventLocationId"
          },
          {
            "name": "Warehouse",
            "dataType": "string",
            "sourceColumn": "WarehouseName"
          },
          {
            "name": "Site",
            "dataType": "string",
            "sourceColumn": "SiteName"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "ColorName"
          },
          {
            "name": "Size",
            "dataType": "string",
            "sourceColumn": "SizeName"
          },
          {
            "name": "Configration",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ConfigrationName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDimension = Source{[Schema=\"dbo\",Item=\"DimDimension\"]}[Data]",
                "in",
                "    dbo_DimDimension"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "EmployeeID",
            "dataType": "string",
            "sourceColumn": "EmployeeAlternativeKey"
          },
          {
            "name": "Employee",
            "dataType": "string",
            "sourceColumn": "EmployeeName"
          },
          {
            "name": "Job",
            "dataType": "string",
            "sourceColumn": "Job"
          },
          {
            "name": "Departmen",
            "dataType": "string",
            "sourceColumn": "DepartmenName"
          },
          {
            "name": "Division",
            "dataType": "string",
            "sourceColumn": "DivisionName"
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender"
          },
          {
            "name": "Contract Type",
            "dataType": "string",
            "sourceColumn": "ContractType"
          },
          {
            "name": "ContractDate",
            "dataType": "dateTime",
            "sourceColumn": "ContractDate"
          },
          {
            "name": "Contract End Date",
            "dataType": "dateTime",
            "sourceColumn": "ContractEndDate"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "Hire Date",
            "dataType": "dateTime",
            "sourceColumn": "HireDate"
          },
          {
            "name": "InsuranceDate",
            "dataType": "dateTime",
            "sourceColumn": "InsuranceDate"
          },
          {
            "name": "Worke Status",
            "dataType": "string",
            "sourceColumn": "WorkeStatus"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    dbo_DimEmployee"
              ]
            }
          }
        ]
      },
      {
        "name": "DimOrderStatus",
        "columns": [
          {
            "name": "StatusKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StatusKey"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "StatusName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixOrderStatus = Source{[Schema=\"dbo\",Item=\"DimFixOrderStatus\"]}[Data]",
                "in",
                "    dbo_DimFixOrderStatus"
              ]
            }
          }
        ]
      },
      {
        "name": "DimSalesType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "Type Name",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixSalesType = Source{[Schema=\"dbo\",Item=\"DimFixSalesType\"]}[Data]",
                "in",
                "    dbo_DimFixSalesType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "GeographyAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyAlternativeKey"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "RegionName"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "StateName"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "CityName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimGeography = Source{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data]",
                "in",
                "    dbo_DimGeography"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyGeography",
            "levels": [
              {
                "name": "Region",
                "ordinal": 0,
                "column": "Region"
              },
              {
                "name": "State",
                "ordinal": 1,
                "column": "State"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City"
              }
            ]
          }
        ]
      },
      {
        "name": "DimMethodAcquisition",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodAcquisitionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionAlternativeKey"
          },
          {
            "name": "Acquisition",
            "dataType": "string",
            "sourceColumn": "NameMethodAcquisition"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodAcquisition = Source{[Schema=\"dbo\",Item=\"DimMethodAcquisition\"]}[Data]",
                "in",
                "    dbo_DimMethodAcquisition"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodDelivery",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodDeliveryKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliveryKey"
          },
          {
            "name": "MethodDeliveryAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliveryAlternativeKey"
          },
          {
            "name": "Delivery",
            "dataType": "string",
            "sourceColumn": "NameMethodDelivery"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodDelivery = Source{[Schema=\"dbo\",Item=\"DimMethodDelivery\"]}[Data]",
                "in",
                "    dbo_DimMethodDelivery"
              ]
            }
          }
        ]
      },
      {
        "name": "DimMethodPayment",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "MethodPaymentKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodPaymentKey"
          },
          {
            "name": "MethodPaymentAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodPaymentAlternativeKey"
          },
          {
            "name": "Payment",
            "dataType": "string",
            "sourceColumn": "NameMethodsPayment"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimMethodPayment = Source{[Schema=\"dbo\",Item=\"DimMethodPayment\"]}[Data]",
                "in",
                "    dbo_DimMethodPayment"
              ]
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "ProductAlternativeKey",
            "dataType": "string",
            "sourceColumn": "ProductAlternativeKey"
          },
          {
            "name": "ProductName",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "SubCategory",
            "dataType": "string",
            "sourceColumn": "SubCategory"
          },
          {
            "name": "StatusCategory",
            "dataType": "string",
            "sourceColumn": "StatusCategory"
          },
          {
            "name": "StatusProduct",
            "dataType": "string",
            "sourceColumn": "StatusProduct"
          },
          {
            "name": "GroupType",
            "dataType": "string",
            "sourceColumn": "GroupType"
          },
          {
            "name": "SalesPrice",
            "dataType": "decimal",
            "sourceColumn": "SalesPrice"
          },
          {
            "name": "PurchasePrice",
            "dataType": "decimal",
            "sourceColumn": "PurchasePrice"
          },
          {
            "name": "StartDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "StartDate"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndDate"
          },
          {
            "name": "Status",
            "dataType": "boolean",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimProduct = Source{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data]",
                "in",
                "    dbo_DimProduct"
              ]
            }
          }
        ]
      },
      {
        "name": "DimPromotion",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "PromotionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionAlternativeKey"
          },
          {
            "name": "STATUS",
            "dataType": "int64",
            "sourceColumn": "STATUS"
          },
          {
            "name": "FROMDATE",
            "dataType": "dateTime",
            "sourceColumn": "FROMDATE"
          },
          {
            "name": "TODATE",
            "dataType": "dateTime",
            "sourceColumn": "TODATE"
          },
          {
            "name": "DELIVERYDATE",
            "dataType": "dateTime",
            "sourceColumn": "DELIVERYDATE"
          },
          {
            "name": "DESCRIPTION",
            "dataType": "string",
            "sourceColumn": "DESCRIPTION"
          },
          {
            "name": "ITEMGROUP",
            "dataType": "string",
            "sourceColumn": "ITEMGROUP"
          },
          {
            "name": "DESCACTIVE",
            "dataType": "int64",
            "sourceColumn": "DESCACTIVE"
          },
          {
            "name": "SORTDISC",
            "dataType": "int64",
            "sourceColumn": "SORTDISC"
          },
          {
            "name": "PRICEDISCOUNT",
            "dataType": "decimal",
            "sourceColumn": "PRICEDISCOUNT"
          },
          {
            "name": "DISCOUNT",
            "dataType": "double",
            "sourceColumn": "DISCOUNT"
          },
          {
            "name": "QUANTITY",
            "dataType": "int64",
            "sourceColumn": "QUANTITY"
          },
          {
            "name": "Location",
            "dataType": "string",
            "sourceColumn": "Location"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimPromotion = Source{[Schema=\"dbo\",Item=\"DimPromotion\"]}[Data]",
                "in",
                "    dbo_DimPromotion"
              ]
            }
          }
        ]
      },
      {
        "name": "DimUnit",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "UnitKey",
            "dataType": "int64",
            "sourceColumn": "UnitKey"
          },
          {
            "name": "UnitAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "UnitAlternativeKey"
          },
          {
            "name": "UnitName",
            "dataType": "string",
            "sourceColumn": "UnitName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimUnit = Source{[Schema=\"dbo\",Item=\"DimUnit\"]}[Data]",
                "in",
                "    dbo_DimUnit"
              ]
            }
          }
        ]
      },
      {
        "name": "DimBranche",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "Branche Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey",
            "formatString": "0",
            "sortByColumn": "Branche Sort"
          },
          {
            "name": "BrancheAlternativeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BrancheAlternativeKey"
          },
          {
            "name": "BrancheName",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BrancheName"
          },
          {
            "name": "UpdatLasteTime",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdatLasteTime",
            "formatString": "General Date"
          },
          {
            "name": "Branche Sort",
            "dataType": "int64",
            "sourceColumn": "BrancheSort",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Branche",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " if([CompanyKey]==3,[BrancheName],[BrancheName] & \" \" & [CompanyKey])",
            "sortByColumn": "Branche Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimBranche = Source{[Schema=\"dbo\",Item=\"DimBranche\"]}[Data]",
                "in",
                "    dbo_DimBranche"
              ]
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "dd-MM-yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"dd-MM-yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "FullDate",
            "dataType": "string",
            "sourceColumn": "FullDate"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeek",
            "dataType": "int64",
            "sourceColumn": "DayOfWeek"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "int64",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "int64",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "int64",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "int64",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "Season",
            "dataType": "string",
            "sourceColumn": "Season"
          },
          {
            "name": "Semester",
            "dataType": "string",
            "sourceColumn": "Semester"
          },
          {
            "name": "IsHoliday",
            "dataType": "boolean",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_DimDate, each Date.IsInPreviousNYears([Date], 10) or Date.IsInCurrentYear([Date]))",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "HierarchyDate",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "DayOfMonth"
              }
            ]
          }
        ]
      },
      {
        "name": "FactSalesOrder",
        "columns": [
          {
            "name": "Sales Order",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "GeographyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyKey"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "CarKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CarKey"
          },
          {
            "name": "MethodAcquisitionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodAcquisitionKey"
          },
          {
            "name": "MethodDeliverykey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MethodDeliverykey"
          },
          {
            "name": "PaymentMethodKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PaymentMethodKey"
          },
          {
            "name": "OrderDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateAlternativeKey"
          },
          {
            "name": "ProductionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductionDateAlternativeKey"
          },
          {
            "name": "ShippingDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShippingDateAlternativeKey"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "OrderDate",
            "displayFolder": "Date"
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "sourceColumn": "ProductionDate",
            "displayFolder": "Date"
          },
          {
            "name": "Shipping Date",
            "dataType": "dateTime",
            "sourceColumn": "ShippingDate",
            "displayFolder": "Date"
          },
          {
            "name": "Discount%",
            "dataType": "double",
            "sourceColumn": "DiscountPercent",
            "displayFolder": "Amount",
            "summarizeBy": "none"
          },
          {
            "name": "DiscountAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DiscountAmount",
            "displayFolder": "Amount"
          },
          {
            "name": "LineAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LineAmount"
          },
          {
            "name": "AmountAfterTax",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountAfterTax",
            "displayFolder": "Amount"
          },
          {
            "name": "TaxAmount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmount"
          },
          {
            "name": "Payment",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Payment",
            "displayFolder": "Amount"
          },
          {
            "name": "Create Date Time",
            "dataType": "dateTime",
            "sourceColumn": "CreateDateTime",
            "displayFolder": "Date"
          },
          {
            "type": "calculated",
            "name": "Payment %",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "ROUNDUP(IFERROR(DIVIDE(FactSalesOrder[Payment],FactSalesOrder[AmountAfterTax]),0),2)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Amount"
          },
          {
            "name": "StatusOrderKey",
            "dataType": "int64",
            "sourceColumn": "StatusOrderKey"
          },
          {
            "name": "TypeKey",
            "dataType": "int64",
            "sourceColumn": "TypeKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSalesOrder = Source{[Schema=\"dbo\",Item=\"FactSalesOrder\"]}[Data]",
                "in",
                "    dbo_FactSalesOrder"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "#Count SO Order",
            "expression": "DISTINCTCOUNT(FactSalesOrder[Sales Order])",
            "displayFolder": "Amount"
          },
          {
            "name": "#Discount Amount",
            "expression": "SUM(FactSalesOrder[DiscountAmount])",
            "displayFolder": "Amount"
          },
          {
            "name": "#Total Amount",
            "expression": "round(sum(FactSalesOrder[AmountAfterTax]),0)",
            "displayFolder": "Amount"
          },
          {
            "name": "#Total Payment",
            "expression": "round(sum(FactSalesOrder[Payment]),0)",
            "displayFolder": "Amount"
          }
        ]
      },
      {
        "name": "FactSalesCommission",
        "columns": [
          {
            "name": "CompanyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CompanyKey"
          },
          {
            "name": "SalesCommissionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionKey"
          },
          {
            "name": "SalesCommissionAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionAlternativeKey"
          },
          {
            "name": "TargetLevelkey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TargetLevelkey"
          },
          {
            "name": "EmpTypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmpTypeKey"
          },
          {
            "name": "EmployeeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "EmployeeKey"
          },
          {
            "name": "BrancheKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "BrancheKey"
          },
          {
            "name": "SalesCommissionDateAlternativeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SalesCommissionDateAlternativeKey"
          },
          {
            "name": "SalesCommissionDateKey",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "SalesCommissionDateKey"
          },
          {
            "name": "Precent",
            "dataType": "double",
            "sourceColumn": "Precent"
          },
          {
            "name": "AmountFrom",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountFrom"
          },
          {
            "name": "AmountTo",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountTo"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Amount"
          },
          {
            "name": "TotalSales",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TotalSales"
          },
          {
            "name": "CountSo",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CountSo"
          },
          {
            "name": "IsDeleted",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "IsDeleted"
          },
          {
            "name": "LastupdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastupdateDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_FactSalesCommission = Source{[Schema=\"dbo\",Item=\"FactSalesCommission\"]}[Data]",
                "in",
                "    dbo_FactSalesCommission"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Commission",
            "expression": "sum(FactSalesCommission[Amount])"
          },
          {
            "name": "Total Sales",
            "expression": "sum(FactSalesCommission[TotalSales])"
          },
          {
            "name": "Count Of SO Commission",
            "expression": "SUM(FactSalesCommission[CountSo])"
          }
        ]
      },
      {
        "name": "DimEmpType",
        "columns": [
          {
            "name": "TypeKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TypeKey"
          },
          {
            "name": "TypeName",
            "dataType": "string",
            "sourceColumn": "TypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimEmpType = Source{[Schema=\"dbo\",Item=\"DimEmpType\"]}[Data]",
                "in",
                "    dbo_DimEmpType"
              ]
            }
          }
        ]
      },
      {
        "name": "DimFixFinTransType",
        "columns": [
          {
            "name": "TransTypeKey",
            "dataType": "int64",
            "sourceColumn": "TransTypeKey"
          },
          {
            "name": "TransTypeName",
            "dataType": "string",
            "sourceColumn": "TransTypeName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/hyperv-srv;DataWarehouse\",",
                "    dbo_DimFixFinTransType = Source{[Schema=\"dbo\",Item=\"DimFixFinTransType\"]}[Data]",
                "in",
                "    dbo_DimFixFinTransType"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "efcc7883-a565-4dfd-9a51-1b3ee580e8a7",
        "fromTable": "FactSales",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "20a4f5a8-dc1b-425c-b945-32227fcfc412",
        "fromTable": "FactSales",
        "fromColumn": "StatusKey",
        "toTable": "DimOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "6f52df78-743c-42be-9b14-6b7827a890b0",
        "fromTable": "FactSales",
        "fromColumn": "TypeKey",
        "toTable": "DimSalesType",
        "toColumn": "TypeKey"
      },
      {
        "name": "a8a9a89f-90b1-4ebc-9808-8437e634cfe2",
        "fromTable": "FactSales",
        "fromColumn": "CarKey",
        "toTable": "DimCar",
        "toColumn": "CarKey"
      },
      {
        "name": "671e7041-af90-4534-9e1d-bf70eee94922",
        "fromTable": "FactSales",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "75b87e4a-c9f4-4381-a2a8-f1fa8687c0fe",
        "fromTable": "FactSales",
        "fromColumn": "DimensionKey",
        "toTable": "DimDimension",
        "toColumn": "DimensionKey"
      },
      {
        "name": "081c882e-a615-4c92-97e5-0d90b34e3524",
        "fromTable": "FactSales",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "7bfbef40-1be6-47d8-b553-00605b9e71fe",
        "fromTable": "FactSales",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "5abc277d-ce70-4f78-996a-190d3de74032",
        "fromTable": "FactSales",
        "fromColumn": "MethodAcquisitionKey",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "d223a52a-cb58-44b7-ae13-70135d56570b",
        "fromTable": "FactSales",
        "fromColumn": "MethodDeliverykey",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "934f097e-9a0a-4860-838e-901584f6065f",
        "fromTable": "FactSales",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "9c161b3d-7507-4639-a51f-72b0560714aa",
        "fromTable": "FactSales",
        "fromColumn": "ProductKey",
        "toTable": "DimProduct",
        "toColumn": "ProductKey"
      },
      {
        "name": "6d62c46f-4e0d-48d7-a479-b881f40f845c",
        "fromTable": "FactSales",
        "fromColumn": "PromotionKey",
        "toTable": "DimPromotion",
        "toColumn": "PromotionKey"
      },
      {
        "name": "a6c99fd9-5295-4781-9f3c-11d58f62b6cc",
        "fromTable": "FactSales",
        "fromColumn": "UnitKey",
        "toTable": "DimUnit",
        "toColumn": "UnitKey"
      },
      {
        "name": "88ffaa6a-2caf-46f6-b43e-8544725699d2",
        "fromTable": "FactSales",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "c4fd38a7-8477-4bac-8505-702a11a9ba54",
        "fromTable": "FactSales",
        "fromColumn": "ProductionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "a34a0957-168b-4eef-9dac-64692bcac096",
        "fromTable": "FactSales",
        "fromColumn": "ShippingDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "b862e642-d68d-4d26-83ad-2f444abcf77b",
        "fromTable": "FactSales",
        "fromColumn": "OrderDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "06188c81-c4cf-422d-b7b5-5621222e0ff6",
        "fromTable": "FactSalesOrder",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "f181d3ab-c2c1-443f-8a5d-5aa2a677423d",
        "fromTable": "FactSalesOrder",
        "fromColumn": "CarKey",
        "toTable": "DimCar",
        "toColumn": "CarKey"
      },
      {
        "name": "7660bf2d-a30f-4bcf-bae0-c038881dd2a8",
        "fromTable": "FactSalesOrder",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "32e2d270-253b-4e04-8a9a-b76e7c3b5af0",
        "fromTable": "FactSalesOrder",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "2d614aad-bb7d-448a-9338-f36da580b64c",
        "fromTable": "FactSalesOrder",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "106d8afe-f5c2-4278-9789-bea2ed54e9c7",
        "fromTable": "FactSalesOrder",
        "fromColumn": "GeographyKey",
        "toTable": "DimGeography",
        "toColumn": "GeographyKey"
      },
      {
        "name": "288f0e24-e57e-4279-add4-21dac18d5bca",
        "fromTable": "FactSalesOrder",
        "fromColumn": "ShippingDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "19022772-562f-4f91-8f70-6bce7e65f9f2",
        "fromTable": "FactSalesOrder",
        "fromColumn": "MethodAcquisitionKey",
        "toTable": "DimMethodAcquisition",
        "toColumn": "MethodAcquisitionKey"
      },
      {
        "name": "8d021442-d847-4f7f-b2d5-6ec66cce5878",
        "fromTable": "FactSalesOrder",
        "fromColumn": "MethodDeliverykey",
        "toTable": "DimMethodDelivery",
        "toColumn": "MethodDeliveryKey"
      },
      {
        "name": "af7e2fde-07f7-450c-8546-2d7ff79e5c45",
        "fromTable": "FactSalesOrder",
        "fromColumn": "PaymentMethodKey",
        "toTable": "DimMethodPayment",
        "toColumn": "MethodPaymentKey"
      },
      {
        "name": "6261b00d-44aa-4c39-8a0b-ff1a4d9a8953",
        "fromTable": "FactSalesOrder",
        "fromColumn": "ProductionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "925a6813-f6c7-4db5-8d09-d0f246819518",
        "fromTable": "FactSalesOrder",
        "fromColumn": "OrderDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "c91cece1-7ba9-4289-bf40-fbcbc253d499",
        "fromTable": "FactSalesOrder",
        "fromColumn": "StatusOrderKey",
        "toTable": "DimOrderStatus",
        "toColumn": "StatusKey"
      },
      {
        "name": "a7a51300-dc16-4fa7-96d6-ee1b8d060343",
        "fromTable": "FactSalesCommission",
        "fromColumn": "CompanyKey",
        "toTable": "DimCompany",
        "toColumn": "Companykey"
      },
      {
        "name": "fec133e3-e7be-4e46-94b9-f992582d577d",
        "fromTable": "FactSalesCommission",
        "fromColumn": "BrancheKey",
        "toTable": "DimBranche",
        "toColumn": "Branche Key"
      },
      {
        "name": "1ee28abb-ea43-4b08-8f26-7f3def0ff1bd",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmployeeKey",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeKey"
      },
      {
        "name": "4cdf3c14-110c-49b2-bcd0-3509dd9c937e",
        "fromTable": "FactSalesCommission",
        "fromColumn": "SalesCommissionDateAlternativeKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "72095038-4166-48fe-9088-9d9dbd41b74d",
        "fromTable": "FactSalesCommission",
        "fromColumn": "EmpTypeKey",
        "toTable": "DimEmpType",
        "toColumn": "TypeKey"
      }
    ],
    "cultures": [
      {
        "name": "ar-EG"
      }
    ],
    "roles": [
      {
        "name": "User",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "DimCompany",
            "filterExpression": "[Companykey]=3"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}